import { SectionFeatureHero } from '@/components/SectionFeatureHero';
import { ProgressActions } from '@/components/ProgressActions';
import { redFlagsDdx } from '@/data/redFlagsDdx';

export default function RedFlagsDdxPage(){return <>
  <SectionFeatureHero title="Red Flags & Differential Diagnosis (D.Dx)" subtitle="Chief-complaint reasoning for the ER: identify danger first, build a differential diagnosis, choose the first safe ED action, and avoid common exam traps." arabic="هذا القسم يعلّمك قاعدة مهمة: قبل أن تبحث عن التشخيص الشائع، استبعد التشخيص الذي يقتل بسرعة." tone="rose"/>
  <section className="grid gap-6">{redFlagsDdx.map((item)=><article key={item.id} className="overflow-hidden rounded-[2rem] border border-slate-200 bg-white shadow-sm">
    <div className="border-b border-slate-100 bg-slate-950 p-6 text-white"><div className="text-xs font-black uppercase tracking-[0.25em] text-rose-200">Chief complaint pathway</div><h2 className="mt-2 text-3xl font-black">{item.presentation}</h2><p className="mt-3 max-w-4xl text-sm leading-7 text-slate-200">{item.chiefComplaint}</p><div className="arabic-support mt-4 rounded-2xl bg-white/10 p-4 text-sm leading-8 text-rose-50">{item.arabicCore}</div></div>
    <div className="grid gap-5 p-6 lg:grid-cols-3"><Panel title="Red flags" items={item.redFlags} danger/><Panel title="Must-not-miss diagnoses" items={item.mustNotMiss} danger/><div className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><h3 className="font-black text-slate-950">First ED action</h3><p className="mt-2 text-sm leading-7 text-slate-700">{item.firstEdAction}</p><h3 className="mt-4 font-black text-slate-950">Disposition</h3><p className="mt-2 text-sm leading-7 text-slate-700">{item.disposition}</p></div></div>
    <div className="grid gap-5 px-6 pb-6 lg:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-white p-4"><h3 className="font-black text-slate-950">Differential diagnosis by system</h3><div className="mt-3 space-y-3">{item.ddxBySystem.map((d)=><div key={d.system} className="rounded-2xl bg-slate-50 p-3"><div className="text-sm font-black text-emerald-700">{d.system}</div><p className="mt-1 text-sm leading-6 text-slate-700">{d.diagnoses.join(' • ')}</p></div>)}</div></div><div className="grid gap-4"><Panel title="Key history questions" items={item.keyQuestions}/><Panel title="Focused exam clues" items={item.focusedExam}/><Panel title="Initial investigations" items={item.initialTests}/></div></div>
    <div className="mx-6 mb-6 rounded-2xl border border-rose-100 bg-rose-50 p-4 text-sm leading-7 text-rose-950"><strong>Common trap:</strong> {item.commonTrap}</div>
    <div className="mx-6 mb-6 rounded-[2rem] border border-emerald-200 bg-emerald-50 p-5"><div className="text-xs font-black uppercase tracking-wider text-emerald-700">Mini MCQ</div><h3 className="mt-2 text-lg font-black text-slate-950">{item.mcq.question}</h3><div className="mt-3 grid gap-2 sm:grid-cols-2">{item.mcq.options.map((opt)=><div key={opt} className={`rounded-2xl border px-4 py-3 text-sm font-bold ${opt===item.mcq.answer?'border-emerald-300 bg-white text-emerald-800':'border-slate-200 bg-white text-slate-700'}`}>{opt}</div>)}</div><p className="mt-3 text-sm leading-7 text-slate-700"><strong>Answer:</strong> {item.mcq.answer}. {item.mcq.explanation}</p><div className="arabic-support mt-3 rounded-2xl bg-white p-3 text-sm leading-7">{item.mcq.arabicTakeaway}</div><ProgressActions id={`ddx-${item.id}`} section="Red Flags & D.Dx" title={item.presentation}/></div>
  </article>)}</section>
</>}
function Panel({title,items,danger=false}:{title:string;items:string[];danger?:boolean}){return <div className={`rounded-2xl border p-4 ${danger?'border-rose-200 bg-rose-50':'border-slate-200 bg-slate-50'}`}><h3 className="font-black text-slate-950">{title}</h3><ul className="mt-3 space-y-2">{items.map((x)=><li key={x} className="text-sm font-semibold leading-6 text-slate-700">• {x}</li>)}</ul></div>}
