import Link from 'next/link';import { InternalPage, GlassCard } from '@/components/InternalPage';import { TopicSectionPager } from '@/components/interns/TopicSectionPager';import { AlertTriangle, Zap, Lightbulb } from 'lucide-react';
const sections=[
{id:'overview',label:'Overview / لمحة',content:(<GlassCard><h2 className="text-base font-black text-white">Ectopic Pregnancy</h2><p className="mt-2 text-sm leading-7 text-slate-400">The #1 cause of first-trimester maternal death. Every woman of reproductive age with abdominal pain or syncope needs a pregnancy test. Ruptured ectopic is a surgical emergency.</p></GlassCard>)},
{id:'recognition',label:'Key Recognition',content:(<div className="grid gap-4 sm:grid-cols-2"><GlassCard><h3 className="text-sm font-black text-white">Clinical Presentation</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Classic triad: amenorrhea + vaginal bleeding + unilateral pelvic pain.</li><li>• Risk factors: PID, previous ectopic, tubal surgery, IUD, smoking.</li><li>• Ruptured: hypotension, peritoneal signs, shoulder tip pain.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Diagnosis</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Urine pregnancy test first (stat).</li><li>• Transvaginal ultrasound: empty uterus + adnexal mass.</li><li>• Serial &beta;-hCG: if &gt;1500-2000 + no IUP → high concern.</li><li>• Abnormal rise (&lt;66% in 48h) suggests ectopic.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Management</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Unstable/ruptured: immediate laparoscopy/laparotomy.</li><li>• Stable, unruptured, &beta;-hCG &lt;5000: methotrexate (if no contraindications).</li><li>• Rh-negative: always give Anti-D immunoglobulin.</li></ul></GlassCard></div>)},
{id:'redflags',label:'Red Flags',content:(<GlassCard className="border-red-500/10 bg-red-500/3"><h2 className="flex items-center gap-2 text-base font-black text-red-300"><AlertTriangle size={18}/> Red Flags</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Syncope + positive pregnancy test → ruptured ectopic until proven otherwise.</li><li>• Hypotension in early pregnancy → hemoperitoneum, activate OBGYN + OR.</li><li>• Shoulder tip pain → diaphragmatic irritation from blood.</li></ul></GlassCard>)},
{id:'nextstep',label:'Best Next Step',content:(<GlassCard><h3 className="text-sm font-black text-white">Suspected Ectopic Protocol</h3><p className="mt-2 text-sm leading-7 text-slate-400">1. ABCDE, 2 large-bore IVs if unstable.<br />2. Stat urine pregnancy test.<br />3. If positive + unstable: activate OBGYN emergently, prepare for OR.<br />4. If stable: transvaginal US + serial &beta;-hCG.</p></GlassCard>)},
{id:'traps',label:'Exam Traps',content:(<GlassCard><h2 className="flex items-center gap-2 text-base font-black text-white"><Zap size={18} className="text-amber-400"/> Common Exam Traps</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Forgetting pregnancy test in any woman of childbearing age.</li><li>• Relying on a single &beta;-hCG value rather than trend.</li><li>• Missing ruptured ectopic in a stable-appearing patient.</li></ul></GlassCard>)},
{id:'arabic',label:'Arabic / عربي',content:(<GlassCard className="border-cyan-500/15 bg-cyan-500/3"><h2 className="flex items-center gap-2 text-base font-black text-cyan-300"><Lightbulb size={18}/> Arabic Explanation</h2><p className="mt-3 text-sm leading-8 text-slate-400">أي أنثى في عمر الإنجاب + ألم بطن أو إغماء = اختبار حمل. الثالوث الكلاسيكي: انقطاع دورة + نزيف مهبلي + ألم حوض وحيد الجانب. هبوط ضغط + حمل إيجابي = حمل خارج الرحم منفجر = غرفة عمليات فورًا. دائماً أعطِ Anti-D إذا كانت الزمرة سالبة.</p></GlassCard>)},
{id:'related',label:'Related',content:(<div className="text-center"><p className="text-xs font-bold text-slate-500">Related:</p><div className="mt-2 flex flex-wrap justify-center gap-2"><Link href="/interns/study/obgyn/early-pregnancy-bleeding" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Early Pregnancy Bleeding</Link><Link href="/interns/study/surgery/fluids-electrolytes-transfusion" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Fluids & Transfusion</Link></div></div>)},
];
export default function EctopicPage(){return(<InternalPage title="Ectopic Pregnancy" subtitle="الحمل خارج الرحم" introText="The #1 cause of first-trimester maternal death. Recognition, diagnosis, and emergency management." backHref="/interns/study/obgyn" backLabel="OB/GYN"><TopicSectionPager sections={sections}/></InternalPage>);}
