import Link from 'next/link';import { InternalPage, GlassCard } from '@/components/InternalPage';import { TopicSectionPager } from '@/components/interns/TopicSectionPager';import { AlertTriangle, Zap, Lightbulb, HeartPulse } from 'lucide-react';
const sections=[
{id:'overview',label:'Overview / لمحة',content:(<GlassCard><h2 className="text-base font-black text-white">Emergency Cardiology</h2><p className="mt-2 text-sm leading-7 text-slate-400">ACS, STEMI/NSTEMI, life-threatening arrhythmias, acute heart failure, and cardiogenic shock — the highest-weight topic in internship exams (~35-40%). Focus on rapid recognition, ECG patterns, and first-step management.</p><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• ACS, arrhythmias, and heart failure are the most tested sub-topics.</li><li>• Interns must recognise STEMI on ECG and know the first 3 steps.</li><li>• Cardiogenic shock vs. other shock types is a classic exam discriminator.</li></ul></GlassCard>)},
{id:'recognition',label:'Key Recognition',content:(<div className="grid gap-4 sm:grid-cols-2"><GlassCard><h3 className="text-sm font-black text-white">ACS / STEMI</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Chest pain + diaphoresis + radiation to left arm/jaw.</li><li>• ECG: ST elevation ≥1mm in 2 contiguous leads (or ≥2mm in V2-V3).</li><li>• Posterior MI: ST depression V1-V3 + tall R waves.</li><li>• Right ventricular MI: STE in V4R, hypotension with nitrates.</li><li>• Troponin rise confirms but do NOT wait for troponin to act.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Heart Failure & Shock</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Acute pulmonary edema: sit upright, CPAP/NIV, IV nitrates, loop diuretic.</li><li>• Cardiogenic shock: cold extremities, low BP, pulmonary congestion.</li><li>• Norepinephrine is first-line vasopressor in cardiogenic shock.</li><li>• Avoid fluid boluses if rales and pulmonary edema are present.</li><li>• Definitive: rapid reperfusion (PCI or thrombolytics).</li></ul></GlassCard></div>)},
{id:'redflags',label:'Red Flags',content:(<GlassCard className="border-red-500/10 bg-red-500/3"><h2 className="flex items-center gap-2 text-base font-black text-red-300"><AlertTriangle size={18}/> Red Flags</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Hypotension + STEMI → right ventricular MI until proven otherwise.</li><li>• New-onset LBBB with chest pain → treat as STEMI equivalent.</li><li>• Syncope + chest pain → aortic dissection, PE, or critical AS.</li><li>• Wide-complex tachycardia + hemodynamic instability → immediate cardioversion.</li></ul></GlassCard>)},
{id:'nextstep',label:'Best Next Step',content:(<GlassCard><h3 className="text-sm font-black text-white">STEMI Protocol</h3><p className="mt-2 text-sm leading-7 text-slate-400">1. Aspirin 300 mg chewable.<br />2. Oxygen if SpO2 &lt;90%.<br />3. Nitroglycerin if no hypotension/RV MI.<br />4. Activate cath lab or give thrombolytic within 30 min.<br />5. P2Y12 inhibitor (ticagrelor/clopidogrel).<br />6. Unstable arrhythmia: synchronized cardioversion if unstable, amiodarone if stable VT.</p></GlassCard>)},
{id:'traps',label:'Exam Traps',content:(<GlassCard><h2 className="flex items-center gap-2 text-base font-black text-white"><Zap size={18} className="text-amber-400"/> Common Exam Traps</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Giving fluid challenges to a hypotensive patient with pulmonary edema.</li><li>• Assuming lung-protective ventilation is only for ICU patients with ARDS.</li><li>• Relying solely on troponin while delaying reperfusion in clear STEMI.</li><li>• Missing right ventricular MI: always check V4R in inferior STEMI.</li><li>• Confusing pericarditis STE (diffuse, concave-up) with STEMI (territorial, convex).</li></ul></GlassCard>)},
{id:'arabic',label:'Arabic / عربي',content:(<GlassCard className="border-cyan-500/15 bg-cyan-500/3"><h2 className="flex items-center gap-2 text-base font-black text-cyan-300"><Lightbulb size={18}/> Arabic Explanation</h2><p className="mt-3 text-sm leading-8 text-slate-400">مريض الجلطة (STEMI): أسبرين فورًا، نيتروجليسيرين إذا ما في هبوط ضغط، تفعيل القسطرة أو إذابة الجلطة خلال 30 دقيقة. لا تتأخر بانتظار التروبونين. مريض الجلطة وضغطه واطي وعنده سوائل ع الرئة — إياك تعطيه سوائل! العلاج الأول: Norepinephrine مع القسطرة فورًا.</p></GlassCard>)},
{id:'related',label:'Related',content:(<div className="text-center"><p className="text-xs font-bold text-slate-500">Related:</p><div className="mt-2 flex flex-wrap justify-center gap-2"><Link href="/interns/study/surgery/fluids-electrolytes-transfusion" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Fluids & Electrolytes</Link><Link href="/interns/ecg-essentials" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">ECG Essentials</Link><Link href="/interns/drug-essentials" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Drug Essentials</Link></div></div>)},
];
export default function EmergencyCardiologyPage(){return(<InternalPage title="Emergency Cardiology" subtitle="طوارئ القلب في الامتياز" introText="ACS, STEMI/NSTEMI, arrhythmias, heart failure, and cardiogenic shock — highest exam weight. Focus on rapid ECG recognition and first-step management." backHref="/interns/study/internal-medicine" backLabel="Internal Medicine"><TopicSectionPager sections={sections}/></InternalPage>);}
