import { SectionFeatureHero } from '@/components/SectionFeatureHero';
import { TopicMatchedVisuals } from '@/components/TopicMatchedVisuals';
import { ProgressActions } from '@/components/ProgressActions';
import { getVisualAssetsForTopic, visualSigns } from '@/lib/database';

export default function VisualSignsPage() {
  return <><SectionFeatureHero title="Visual Signs" subtitle="A bedside visual recognition atlas: clinical signs, image clues, normal-vs-abnormal thinking, associated conditions, red flags, and exam traps." arabic="العلامة البصرية تساعدك ترى التشخيص قبل أن تحفظ النص. في كل علامة نسأل: ماذا أرى؟ ماذا تعني؟ وما الخطر الذي لا يجب تفويته؟" tone="blue" />
  <section className="grid gap-6">{visualSigns.map((s:any,i:number)=>{const visuals=getVisualAssetsForTopic(s.topic||s.text, undefined, 3); return <article key={s.id||i} className="overflow-hidden rounded-[2rem] border border-slate-200 bg-white shadow-sm"><div className="grid gap-0 lg:grid-cols-[0.95fr_1.05fr]"><div className="bg-slate-950 p-6 text-white"><div className="text-xs font-black uppercase tracking-wider text-blue-200">Visual clinical clue</div><h2 className="mt-2 text-3xl font-black">{s.topic}</h2><p className="mt-3 text-sm leading-7 text-slate-200">{s.text}</p><div className="arabic-support mt-4 rounded-2xl bg-white/10 p-4 text-sm leading-8 text-blue-50">ابدأ من الصورة أو العلامة: ماذا أرى؟ أين تظهر؟ أي تشخيص خطير يجب أن أفكر فيه؟ لا تحفظ الاسم فقط.</div></div><div className="p-6">{visuals.length ? <TopicMatchedVisuals assets={visuals as any[]} title={`${s.topic} — related visuals`} subtitle="Topic-matched visuals only; raw cover/intro pages are filtered out." limit={3}/> : <div className="rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-6 text-sm font-bold text-slate-500">Visual mapping pending: this sign needs a clinically relevant image/diagram from the PDF review system.</div>}</div></div><div className="grid gap-4 p-6 md:grid-cols-2 xl:grid-cols-4"><Info title="How to recognize" text="Look for the visual pattern first, then connect it to the dangerous condition."/><Info title="Associated condition" text={s.topic}/><Info title="Red flag logic" text="If the sign suggests a time-sensitive emergency, prioritize stabilization and urgent consultation."/><Info title="Exam trap" text="Do not confuse the name of the sign with the action required in the ED."/></div><div className="mx-6 mb-6 rounded-2xl bg-emerald-50 p-4 text-sm leading-7 text-slate-800"><strong>Arabic support:</strong> العلامة ليست هدفًا بحد ذاتها؛ الهدف أن تقودك بسرعة إلى التشخيص الخطير أو القرار الصحيح.</div><div className="mx-6 mb-6"><ProgressActions id={`visual-sign-${s.id||i}`} section="Visual Signs" title={s.topic}/></div></article>})}</section></>;
}
function Info({title,text}:{title:string;text:string}){return <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><h3 className="text-sm font-black text-slate-950">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{text}</p></div>}
