import Link from 'next/link';import { InternalPage, GlassCard } from '@/components/InternalPage';import { TopicSectionPager } from '@/components/interns/TopicSectionPager';import { AlertTriangle, Zap, Lightbulb } from 'lucide-react';
const sections=[
{id:'overview',label:'Overview / لمحة',content:(<GlassCard><h2 className="text-base font-black text-white">Trauma</h2><p className="mt-2 text-sm leading-7 text-slate-400">ABCDE approach, ATLS principles, head/chest/abdominal trauma, burns, and shock — trauma is the leading cause of death in young adults. Every intern must know the primary and secondary survey.</p></GlassCard>)},
{id:'recognition',label:'Key Recognition',content:(<div className="grid gap-4 sm:grid-cols-2"><GlassCard><h3 className="text-sm font-black text-white">Primary Survey (ABCDE)</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• A: Airway + C-spine protection. Talk = patent airway.</li><li>• B: Breathing — inspect, auscultate, pulse ox, life-threatening injuries.</li><li>• C: Circulation — BP, HR, pulses, IV access, control bleeding.</li><li>• D: Disability — GCS, pupils, glucose.</li><li>• E: Exposure — full exam, prevent hypothermia.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Head Injury</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• GCS &le;8 = intubate. CT head per NICE/Canadian rules.</li><li>• ICP management: head elevation 30°, mannitol/hypertonic saline.</li><li>• Avoid hypotension + hypoxia (secondary brain injury).</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Chest Trauma</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Tension pneumothorax: tracheal deviation, absent breath sounds, hypotension.</li><li>• Needle decompression: 2nd ICS midclavicular → chest tube.</li><li>• Cardiac tamponade: Beck triad (hypotension, muffled sounds, JVD).</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Burns</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Rule of nines. Parkland formula: 4 mL × kg × %TBSA (½ over 8h, ½ over 16h).</li><li>• Inhalation injury: stridor, carbonaceous sputum, facial burns → early intubation.</li></ul></GlassCard></div>)},
{id:'redflags',label:'Red Flags',content:(<GlassCard className="border-red-500/10 bg-red-500/3"><h2 className="flex items-center gap-2 text-base font-black text-red-300"><AlertTriangle size={18}/> Red Flags</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• GCS drop of 2+ points → urgent CT, neurosurgery.</li><li>• Tracheal deviation + absent breath sounds → needle decompression NOW.</li><li>• Hypotension refractory to fluids → ongoing hemorrhage, activate MTP.</li><li>• Burns + stridor → early intubation before airway swells.</li></ul></GlassCard>)},
{id:'nextstep',label:'Best Next Step',content:(<GlassCard><h3 className="text-sm font-black text-white">Massive Transfusion Protocol</h3><p className="mt-2 text-sm leading-7 text-slate-400">1. Activate MTP early in major hemorrhage.<br />2. 1:1:1 ratio (PRBCs:FFP:platelets).<br />3. Tranexamic acid 1g IV within 3h.<br />4. Calcium replacement (citrate toxicity).<br />5. Target: maintain perfusion, not specific Hb.</p></GlassCard>)},
{id:'traps',label:'Exam Traps',content:(<GlassCard><h2 className="flex items-center gap-2 text-base font-black text-white"><Zap size={18} className="text-amber-400"/> Common Exam Traps</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Forgetting C-spine immobilization in any trauma patient.</li><li>• Delaying needle decompression for tension pneumothorax.</li><li>• Over-resuscitating with crystalloid in hemorrhagic shock.</li></ul></GlassCard>)},
{id:'arabic',label:'Arabic / عربي',content:(<GlassCard className="border-cyan-500/15 bg-cyan-500/3"><h2 className="flex items-center gap-2 text-base font-black text-cyan-300"><Lightbulb size={18}/> Arabic Explanation</h2><p className="mt-3 text-sm leading-8 text-slate-400">المسح الأولي: A airway + تثبيت الرقبة، B تنفس، C دوران + إيقاف النزيف، D فحص عصبي، E كشف كامل. استرواح الصدر الضاغط: إبرة في الحيز الوربي الثاني + أنبوب صدري. الحروق: قاعدة التسعات + محلول باركلاند (4 × الوزن × % الحرق).</p></GlassCard>)},
{id:'related',label:'Related',content:(<div className="text-center"><p className="text-xs font-bold text-slate-500">Related:</p><div className="mt-2 flex flex-wrap justify-center gap-2"><Link href="/interns/study/surgery/fluids-electrolytes-transfusion" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Fluids & Transfusion</Link><Link href="/interns/study/surgery/acute-abdomen" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Acute Abdomen</Link></div></div>)},
];
export default function TraumaPage(){return(<InternalPage title="Trauma" subtitle="الإصابات والرضوض" introText="ABCDE, ATLS principles, head/chest/abdominal trauma, burns, and shock. Every intern must know the primary survey." backHref="/interns/study/surgery" backLabel="Surgery"><TopicSectionPager sections={sections}/></InternalPage>);}
