import Link from 'next/link';import { InternalPage, GlassCard } from '@/components/InternalPage';import { TopicSectionPager } from '@/components/interns/TopicSectionPager';import { AlertTriangle, Zap, Lightbulb } from 'lucide-react';
const sections=[
{id:'overview',label:'Overview / لمحة',content:(<GlassCard><h2 className="text-base font-black text-white">Basic Surgical Procedures</h2><p className="mt-2 text-sm leading-7 text-slate-400">Cannulation, NG tube, Foley catheter, suturing, drains, and basic airway procedures — these are the practical skills interns perform daily. Know the indications, technique, and complications.</p></GlassCard>)},
{id:'recognition',label:'Key Recognition',content:(<div className="grid gap-4 sm:grid-cols-2"><GlassCard><h3 className="text-sm font-black text-white">IV Cannulation</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Indications: IV fluids, medications, blood products.</li><li>• Sites: hand veins, forearm, antecubital fossa.</li><li>• Gauge: 14-16G for resuscitation, 18-20G for routine, 22-24G for pediatrics.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">NG Tube</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Indications: bowel obstruction, gastric decompression, feeding.</li><li>• Contraindications: basal skull fracture, esophageal varices (relative).</li><li>• Confirm position: aspirate + pH, CXR.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Foley Catheter</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Indications: urinary retention, output monitoring, pelvic surgery.</li><li>• Contraindications: suspected urethral injury (blood at meatus, high-riding prostate).</li><li>• Complications: UTI, trauma, false passage.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Suturing Basics</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Simple interrupted: most common, good for most wounds.</li><li>• Mattress: vertical/horizontal, for wound edge eversion.</li><li>• Subcuticular: cosmetic closure, absorbable suture.</li><li>• Remove sutures: face 5 days, scalp 7, trunk 7-10, extremities 10-14.</li></ul></GlassCard></div>)},
{id:'redflags',label:'Red Flags',content:(<GlassCard className="border-red-500/10 bg-red-500/3"><h2 className="flex items-center gap-2 text-base font-black text-red-300"><AlertTriangle size={18}/> Red Flags</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Blood at urethral meatus → do NOT catheterize (urethral injury), retrograde urethrogram first.</li><li>• NG tube in basal skull fracture → risk of intracranial placement.</li><li>• Infected wound sutured closed → abscess formation.</li></ul></GlassCard>)},
{id:'nextstep',label:'Best Next Step',content:(<GlassCard><h3 className="text-sm font-black text-white">Pre-Procedure Checklist</h3><p className="mt-2 text-sm leading-7 text-slate-400">1. Explain procedure to patient, obtain consent.<br />2. Gather equipment, check sterility.<br />3. Position patient appropriately.<br />4. Perform timeout if invasive.<br />5. Document: procedure, indication, complications, who performed.</p></GlassCard>)},
{id:'traps',label:'Exam Traps',content:(<GlassCard><h2 className="flex items-center gap-2 text-base font-black text-white"><Zap size={18} className="text-amber-400"/> Common Exam Traps</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Catheterizing a patient with urethral injury signs.</li><li>• Not checking NG position before feeding (must confirm with CXR).</li><li>• Suturing a wound that should be left open (dirty/infected).</li></ul></GlassCard>)},
{id:'arabic',label:'Arabic / عربي',content:(<GlassCard className="border-cyan-500/15 bg-cyan-500/3"><h2 className="flex items-center gap-2 text-base font-black text-cyan-300"><Lightbulb size={18}/> Arabic Explanation</h2><p className="mt-3 text-sm leading-8 text-slate-400">الكانيولا: 16-14G للإنعاش، 20-18G للاستعمال العادي. الأنبوب الأنفي المعدي: ممنوع في كسر قاعدة الجمجمة. القسطرة البولية: ممنوعة إذا كان هناك دم في فتحة البول (إصابة إحليل). إزالة الغرز: الوجه 5 أيام، الجذع 7-10 أيام، الأطراف 10-14 يومًا.</p></GlassCard>)},
{id:'related',label:'Related',content:(<div className="text-center"><p className="text-xs font-bold text-slate-500">Related:</p><div className="mt-2 flex flex-wrap justify-center gap-2"><Link href="/interns/study/surgery/surgical-basics" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Surgical Basics</Link><Link href="/interns/study/surgery/wounds-infections" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Wounds & Infections</Link></div></div>)},
];
export default function ProceduresPage(){return(<InternalPage title="Procedures" subtitle="الإجراءات الجراحية الأساسية" introText="Cannulation, NG tube, Foley catheter, suturing, and drains. Practical skills every intern performs daily." backHref="/interns/study/surgery" backLabel="Surgery"><TopicSectionPager sections={sections}/></InternalPage>);}
