import Link from 'next/link';import { InternalPage, GlassCard } from '@/components/InternalPage';import { TopicSectionPager } from '@/components/interns/TopicSectionPager';import { AlertTriangle, Zap, Lightbulb, Droplets } from 'lucide-react';
const sections=[
{id:'overview',label:'Overview / لمحة',content:(<GlassCard><h2 className="text-base font-black text-white">Fluids, Electrolytes & Transfusion</h2><p className="mt-2 text-sm leading-7 text-slate-400">Surgical fluid management, electrolyte emergencies, and blood transfusion basics — cross-specialty knowledge tested in every internship exam. Focus on calculations, recognition, and safe transfusion practice.</p><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Maintenance fluid calculations: 100/50/20 rule.</li><li>• Hyperkalemia ECG: peaked T, wide QRS, sine wave.</li><li>• Transfusion reactions: stop immediately, investigate.</li></ul></GlassCard>)},
{id:'recognition',label:'Key Recognition',content:(<div className="grid gap-4 sm:grid-cols-2"><GlassCard><h3 className="text-sm font-black text-white">Fluids</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• 100/50/20 rule: first 10 kg × 100, next 10 × 50, &gt;20 × 20 mL/day.</li><li>• 4/2/1 rule for hourly rate.</li><li>• Standard maintenance: 0.45% NaCl + 5% dextrose + 20 mEq/L KCl.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Electrolytes</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Hyperkalemia: calcium gluconate FIRST if ECG changes.</li><li>• Hyponatremia: correct slowly (max 8-12 mEq/24h).</li><li>• Rapid Na correction → central pontine myelinolysis.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Transfusion</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• 1 unit PRBCs raises Hb ~1 g/dL.</li><li>• Transfusion threshold: Hb &lt;7 (stable), &lt;8 (cardiac).</li><li>• MTP: 1:1:1 ratio (PRBCs:FFP:platelets).</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Transfusion Reactions</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Acute hemolytic: fever, chills, flank pain → STOP, investigate.</li><li>• Anaphylactic: hypotension, bronchospasm → STOP, epinephrine IM.</li><li>• TRALI: respiratory distress within 6h → STOP, supportive care.</li></ul></GlassCard></div>)},
{id:'redflags',label:'Red Flags',content:(<GlassCard className="border-red-500/10 bg-red-500/3"><h2 className="flex items-center gap-2 text-base font-black text-red-300"><AlertTriangle size={18}/> Red Flags</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Hyperkalemia + ECG changes → calcium gluconate STAT.</li><li>• Fever + flank pain during transfusion → acute hemolytic reaction.</li><li>• Rapid Na correction → irreversible brain damage.</li><li>• Hypotension + urticaria during transfusion → anaphylaxis.</li></ul></GlassCard>)},
{id:'nextstep',label:'Best Next Step',content:(<GlassCard><h3 className="text-sm font-black text-white">Transfusion Reaction Protocol</h3><p className="mt-2 text-sm leading-7 text-slate-400">1. STOP the transfusion immediately.<br />2. Keep IV line open with normal saline.<br />3. Check vitals, verify patient ID + blood unit label.<br />4. Send: CBC, Coombs, haptoglobin, LDH, repeat crossmatch.<br />5. Return blood unit + tubing to blood bank.</p></GlassCard>)},
{id:'traps',label:'Exam Traps',content:(<GlassCard><h2 className="flex items-center gap-2 text-base font-black text-white"><Zap size={18} className="text-amber-400"/> Common Exam Traps</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Giving insulin+glucose before calcium in hyperkalemia with ECG changes.</li><li>• Correcting chronic hyponatremia too rapidly.</li><li>• Using Lactated Ringer in hyperkalemia (contains K+).</li></ul></GlassCard>)},
{id:'arabic',label:'Arabic / عربي',content:(<GlassCard className="border-cyan-500/15 bg-cyan-500/3"><h2 className="flex items-center gap-2 text-base font-black text-cyan-300"><Lightbulb size={18}/> Arabic Explanation</h2><p className="mt-3 text-sm leading-8 text-slate-400">قاعدة السوائل: 100/50/20. بوتاسيوم عالي + تغيرات تخطيط: غلوكونات كالسيوم فورًا. أي حرارة أو ألم أثناء نقل الدم = أوقف النقل فورًا. لا تصحح الصوديوم المنخفض بسرعة — خطر تلف جذع الدماغ.</p></GlassCard>)},
{id:'related',label:'Related',content:(<div className="text-center"><p className="text-xs font-bold text-slate-500">Related:</p><div className="mt-2 flex flex-wrap justify-center gap-2"><Link href="/interns/study/surgery/acute-abdomen" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Acute Abdomen</Link><Link href="/interns/study/internal-medicine/emergency-cardiology" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Emergency Cardiology</Link></div></div>)},
];
export default function FluidsPage(){return(<InternalPage title="Fluids, Electrolytes & Transfusion" subtitle="السوائل والأملاح ونقل الدم" introText="Fluid calculations, electrolyte emergencies, and transfusion basics. Cross-specialty, always tested." backHref="/interns/study/surgery" backLabel="Surgery"><TopicSectionPager sections={sections}/></InternalPage>);}
