import Link from 'next/link';import { InternalPage, GlassCard } from '@/components/InternalPage';import { TopicSectionPager } from '@/components/interns/TopicSectionPager';import { AlertTriangle, Zap, Lightbulb } from 'lucide-react';
const sections=[
{id:'overview',label:'Overview / لمحة',content:(<GlassCard><h2 className="text-base font-black text-white">Neurology Emergencies</h2><p className="mt-2 text-sm leading-7 text-slate-400">Stroke, seizure, meningitis, altered mental status, and SAH — time-sensitive emergencies where minutes matter. Interns must recognize these and activate the appropriate pathway immediately.</p></GlassCard>)},
{id:'recognition',label:'Key Recognition',content:(<div className="grid gap-4 sm:grid-cols-2"><GlassCard><h3 className="text-sm font-black text-white">Stroke</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Sudden focal neurological deficit. FAST: Face, Arms, Speech, Time.</li><li>• CT head non-contrast first (rule out hemorrhage).</li><li>• Ischemic: thrombolysis within 4.5h if eligible.</li><li>• Hemorrhagic: reverse anticoagulation, BP control, neurosurgery.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Seizure</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Status epilepticus: seizure &gt;5 min or incomplete recovery between seizures.</li><li>• First-line: benzodiazepine (lorazepam IV, midazolam IM).</li><li>• Second-line: levetiracetam, phenytoin, valproate.</li><li>• Check glucose immediately — hypoglycemia mimics seizure.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">SAH</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Thunderclap headache — worst headache of life.</li><li>• CT non-contrast within 6h. If negative: LP for xanthochromia.</li><li>• Nimodipine for vasospasm prevention.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Altered Mental Status</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• AEIOU TIPS mnemonic.</li><li>• Check glucose + naloxone if indicated.</li><li>• CT head if trauma, focal signs, or unexplained.</li></ul></GlassCard></div>)},
{id:'redflags',label:'Red Flags',content:(<GlassCard className="border-red-500/10 bg-red-500/3"><h2 className="flex items-center gap-2 text-base font-black text-red-300"><AlertTriangle size={18}/> Red Flags</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Sudden worst headache + neck stiffness → SAH until proven otherwise.</li><li>• Focal neurological deficit with time of onset &lt;4.5h → activate stroke pathway.</li><li>• Seizure not stopping after 5 min → status epilepticus, ICU.</li><li>• Altered mental status + fever + neck stiffness → meningitis.</li></ul></GlassCard>)},
{id:'nextstep',label:'Best Next Step',content:(<GlassCard><h3 className="text-sm font-black text-white">Suspected Stroke Pathway</h3><p className="mt-2 text-sm leading-7 text-slate-400">1. ABCDE, check glucose, establish time of onset.<br />2. CT head non-contrast STAT.<br />3. If ischemic + within 4.5h + no contraindications: thrombolysis.<br />4. If hemorrhagic: BP control, reverse anticoagulation, neurosurgery consult.<br />5. Admit to stroke unit.</p></GlassCard>)},
{id:'traps',label:'Exam Traps',content:(<GlassCard><h2 className="flex items-center gap-2 text-base font-black text-white"><Zap size={18} className="text-amber-400"/> Common Exam Traps</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Not checking glucose in a patient with seizure or AMS.</li><li>• Missing SAH when CT is negative but LP was not performed.</li><li>• Treating hypertension aggressively in acute ischemic stroke.</li></ul></GlassCard>)},
{id:'arabic',label:'Arabic / عربي',content:(<GlassCard className="border-cyan-500/15 bg-cyan-500/3"><h2 className="flex items-center gap-2 text-base font-black text-cyan-300"><Lightbulb size={18}/> Arabic Explanation</h2><p className="mt-3 text-sm leading-8 text-slate-400">جلطة الدماغ = عجز عصبي مفاجئ. أهم خطوة: أشعة مقطعية فورًا لاستبعاد النزيف. إذا نقص تروية خلال 4.5 ساعة = إذابة الجلطة. الصراع المستمر لأكثر من 5 دقائق = حالة صرعية. افحص السكر أولًا دائمًا في أي تشنج أو تغير وعي.</p></GlassCard>)},
{id:'related',label:'Related',content:(<div className="text-center"><p className="text-xs font-bold text-slate-500">Related:</p><div className="mt-2 flex flex-wrap justify-center gap-2"><Link href="/interns/study/internal-medicine/emergency-cardiology" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Emergency Cardiology</Link><Link href="/interns/study/internal-medicine/infectious-disease" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Infectious Disease</Link></div></div>)},
];
export default function NeuroPage(){return(<InternalPage title="Neurology Emergencies" subtitle="طوارئ الأعصاب في الامتياز" introText="Stroke, seizure, meningitis, SAH, and altered mental status. Focus on time-sensitive recognition and pathway activation." backHref="/interns/study/internal-medicine" backLabel="Internal Medicine"><TopicSectionPager sections={sections}/></InternalPage>);}
