import Link from 'next/link';import { InternalPage, GlassCard } from '@/components/InternalPage';import { TopicSectionPager } from '@/components/interns/TopicSectionPager';import { AlertTriangle, Zap, Lightbulb } from 'lucide-react';
const sections=[
{id:'overview',label:'Overview / لمحة',content:(<GlassCard><h2 className="text-base font-black text-white">Labor & Delivery</h2><p className="mt-2 text-sm leading-7 text-slate-400">Labor stages, CTG basics, delivery complications, and obstetric emergencies. Interns in the delivery suite must recognize normal vs. abnormal progress and when to escalate.</p></GlassCard>)},
{id:'recognition',label:'Key Recognition',content:(<div className="grid gap-4 sm:grid-cols-2"><GlassCard><h3 className="text-sm font-black text-white">Labor Stages</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• First stage: onset of contractions → full cervical dilation (10 cm). Latent + active phases.</li><li>• Second stage: full dilation → delivery of fetus.</li><li>• Third stage: delivery of fetus → delivery of placenta (&lt;30 min).</li><li>• Fourth stage: first hour postpartum (monitor for PPH).</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">CTG Basics</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Baseline: 110-160 bpm. Bradycardia &lt;110, tachycardia &gt;160.</li><li>• Variability: reassuring 6-25 bpm. Reduced &lt;5 bpm = concerning.</li><li>• Accelerations: reassuring (2+ in 20 min).</li><li>• Decelerations: early (head compression), late (uteroplacental insufficiency), variable (cord compression).</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Obstetric Emergencies</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Cord prolapse: elevate presenting part, emergency C-section.</li><li>• Shoulder dystocia: McRoberts maneuver, suprapubic pressure.</li><li>• Uterine rupture: sudden pain, loss of contractions, fetal distress.</li></ul></GlassCard></div>)},
{id:'redflags',label:'Red Flags',content:(<GlassCard className="border-red-500/10 bg-red-500/3"><h2 className="flex items-center gap-2 text-base font-black text-red-300"><AlertTriangle size={18}/> Red Flags on CTG</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Prolonged deceleration &gt;3 min → emergency, possible cord prolapse/abruption.</li><li>• Late decelerations + reduced variability → fetal hypoxia, urgent delivery.</li><li>• Sinusoidal pattern → severe fetal anemia, needs immediate action.</li></ul></GlassCard>)},
{id:'nextstep',label:'Best Next Step',content:(<GlassCard><h3 className="text-sm font-black text-white">CTG Interpretation (DR C BRAVADO)</h3><p className="mt-2 text-sm leading-7 text-slate-400">DR: Define Risk (maternal/fetal risk factors).<br />C: Contractions (frequency, duration).<br />BRA: Baseline Rate (110-160).<br />V: Variability (6-25 reassuring).<br />A: Accelerations (present = reassuring).<br />D: Decelerations (early/late/variable).<br />O: Overall assessment (reassuring/non-reassuring/abnormal).</p></GlassCard>)},
{id:'traps',label:'Exam Traps',content:(<GlassCard><h2 className="flex items-center gap-2 text-base font-black text-white"><Zap size={18} className="text-amber-400"/> Common Exam Traps</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Confusing early vs. late decelerations (timing relative to contraction peak).</li><li>• Missing reduced variability as a sign of fetal compromise.</li><li>• Not considering cord prolapse with sudden prolonged deceleration.</li></ul></GlassCard>)},
{id:'arabic',label:'Arabic / عربي',content:(<GlassCard className="border-cyan-500/15 bg-cyan-500/3"><h2 className="flex items-center gap-2 text-base font-black text-cyan-300"><Lightbulb size={18}/> Arabic Explanation</h2><p className="mt-3 text-sm leading-8 text-slate-400">مراحل الولادة: الأولى (توسع عنق الرحم)، الثانية (خروج الجنين)، الثالثة (خروج المشيمة)، الرابعة (أول ساعة). CTG: المعدل الطبيعي 110-160. التباطؤات المتأخرة = نقص أكسجة الجنين. انخفاض التغيرات مع تباطؤات متأخرة = ولادة عاجلة.</p></GlassCard>)},
{id:'related',label:'Related',content:(<div className="text-center"><p className="text-xs font-bold text-slate-500">Related:</p><div className="mt-2 flex flex-wrap justify-center gap-2"><Link href="/interns/study/obgyn/postpartum-hemorrhage" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Postpartum Hemorrhage</Link><Link href="/interns/study/obgyn/hypertensive-disorders" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Hypertensive Disorders</Link></div></div>)},
];
export default function LaborPage(){return(<InternalPage title="Labor & Delivery" subtitle="الولادة ومضاعفاتها" introText="Labor stages, CTG basics, and obstetric emergencies. CTG interpretation is a core intern skill." backHref="/interns/study/obgyn" backLabel="OB/GYN"><TopicSectionPager sections={sections}/></InternalPage>);}
