import Link from 'next/link';import { InternalPage, GlassCard } from '@/components/InternalPage';import { TopicSectionPager } from '@/components/interns/TopicSectionPager';import { AlertTriangle, Zap, Lightbulb } from 'lucide-react';
const sections=[
{id:'overview',label:'Overview / لمحة',content:(<GlassCard><h2 className="text-base font-black text-white">Infectious Disease Emergencies</h2><p className="mt-2 text-sm leading-7 text-slate-400">Sepsis, febrile neutropenia, meningitis, and TB emergencies — recognizing sepsis early and starting antibiotics within 1 hour saves lives. Every intern must know the sepsis bundle.</p></GlassCard>)},
{id:'recognition',label:'Key Recognition',content:(<div className="grid gap-4 sm:grid-cols-2"><GlassCard><h3 className="text-sm font-black text-white">Sepsis</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Life-threatening organ dysfunction (SOFA &ge;2) due to infection.</li><li>• qSOFA: AMS, SBP &le;100, RR &ge;22. &ge;2 = high risk.</li><li>• Lactate, blood cultures, antibiotics within 1 hour, IV fluids 30 mL/kg.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Febrile Neutropenia</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• ANC &lt;500 + single temp &ge;38.3 or sustained &ge;38.</li><li>• Oncology emergency — start empiric antibiotics immediately.</li><li>• Do NOT wait for culture results.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Meningitis</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Fever, headache, neck stiffness, photophobia.</li><li>• LP unless contraindicated (focal neuro signs, papilledema, seizure, GCS&lt;12).</li><li>• Antibiotics + dexamethasone within 1 hour. Do not delay for LP.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">TB Emergencies</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Miliary TB: disseminated, CXR shows millet-seed pattern.</li><li>• TB meningitis: basilar enhancement, hydrocephalus.</li><li>• Isolate if pulmonary TB suspected. Start ATT + steroids for CNS involvement.</li></ul></GlassCard></div>)},
{id:'redflags',label:'Red Flags',content:(<GlassCard className="border-red-500/10 bg-red-500/3"><h2 className="flex items-center gap-2 text-base font-black text-red-300"><AlertTriangle size={18}/> Red Flags</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Lactate &gt;4 + hypotension despite fluids → septic shock, ICU.</li><li>• Fever + neutropenia → emergency antibiotics, do not delay.</li><li>• Purpuric rash + fever → meningococcemia, isolate, antibiotics STAT.</li><li>• Altered mental status + fever → meningitis/encephalitis, LP + empiric treatment.</li></ul></GlassCard>)},
{id:'nextstep',label:'Best Next Step',content:(<GlassCard><h3 className="text-sm font-black text-white">Sepsis Hour-1 Bundle</h3><p className="mt-2 text-sm leading-7 text-slate-400">1. Measure lactate (remeasure if &gt;2).<br />2. Blood cultures before antibiotics (do not delay antibiotics).<br />3. Broad-spectrum antibiotics within 1 hour.<br />4. IV crystalloid 30 mL/kg for hypotension/lactate &ge;4.<br />5. Vasopressors if fluid-refractory.</p></GlassCard>)},
{id:'traps',label:'Exam Traps',content:(<GlassCard><h2 className="flex items-center gap-2 text-base font-black text-white"><Zap size={18} className="text-amber-400"/> Common Exam Traps</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Delaying antibiotics for LP in meningitis — antibiotics first.</li><li>• Relying on SIRS criteria to define sepsis (now use SOFA/qSOFA).</li><li>• Missing febrile neutropenia in a chemo patient with &ldquo;low-grade fever.&rdquo;</li></ul></GlassCard>)},
{id:'arabic',label:'Arabic / عربي',content:(<GlassCard className="border-cyan-500/15 bg-cyan-500/3"><h2 className="flex items-center gap-2 text-base font-black text-cyan-300"><Lightbulb size={18}/> Arabic Explanation</h2><p className="mt-3 text-sm leading-8 text-slate-400">الإنتان = فشل أعضاء بسبب العدوى. أهم خطوة: مضادات حيوية وريدية خلال ساعة + سوائل 30 مل/كغ. لا تؤخر المضاد الحيوي بسبب البزل القطني في التهاب السحايا. الحرارة مع نقص الخلايا المتعادلة = حالة طارئة في مريض الأورام.</p></GlassCard>)},
{id:'related',label:'Related',content:(<div className="text-center"><p className="text-xs font-bold text-slate-500">Related:</p><div className="mt-2 flex flex-wrap justify-center gap-2"><Link href="/interns/study/internal-medicine/respiratory-emergencies" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Respiratory Emergencies</Link><Link href="/interns/drug-essentials" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Drug Essentials</Link></div></div>)},
];
export default function IDPage(){return(<InternalPage title="Infectious Disease" subtitle="الأمراض المعدية الطارئة في الامتياز" introText="Sepsis, febrile neutropenia, meningitis, and TB emergencies. Focus on early recognition and the hour-1 sepsis bundle." backHref="/interns/study/internal-medicine" backLabel="Internal Medicine"><TopicSectionPager sections={sections}/></InternalPage>);}
