import Link from 'next/link';import { InternalPage, GlassCard } from '@/components/InternalPage';import { TopicSectionPager } from '@/components/interns/TopicSectionPager';import { AlertTriangle, Zap, Lightbulb } from 'lucide-react';
const sections=[
{id:'overview',label:'Overview / لمحة',content:(<GlassCard><h2 className="text-base font-black text-white">Nephrology & Electrolytes</h2><p className="mt-2 text-sm leading-7 text-slate-400">AKI, CKD emergencies, hyperkalemia, hyponatremia, and acid-base disorders — cross-specialty topics tested in every exam. Interns must recognize life-threatening electrolyte abnormalities on ECG.</p></GlassCard>)},
{id:'recognition',label:'Key Recognition',content:(<div className="grid gap-4 sm:grid-cols-2"><GlassCard><h3 className="text-sm font-black text-white">Hyperkalemia</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• ECG: peaked T → flat P → wide QRS → sine wave.</li><li>• Causes: renal failure, cell lysis, acidosis, drugs (ACEi, spironolactone).</li><li>• Calcium gluconate FIRST if ECG changes (stabilizes membrane).</li><li>• Then shift K+: insulin+glucose, salbutamol, bicarbonate.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Hyponatremia</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Correct slowly: max 8-12 mEq/L per 24h.</li><li>• Rapid correction → central pontine myelinolysis.</li><li>• SIADH, diuretics, hypovolemia, heart failure.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">AKI</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Pre-renal: hypovolemia, hypotension. Renal: ATN, AIN. Post-renal: obstruction.</li><li>• Urine output &lt;0.5 mL/kg/h, rising creatinine.</li><li>• Treat cause, avoid nephrotoxins, manage hyperkalemia.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Acid-Base</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Metabolic acidosis: DKA, renal failure, lactate, toxins.</li><li>• Metabolic alkalosis: vomiting, diuretics.</li><li>• Respiratory: COPD (acidosis), hyperventilation (alkalosis).</li></ul></GlassCard></div>)},
{id:'redflags',label:'Red Flags',content:(<GlassCard className="border-red-500/10 bg-red-500/3"><h2 className="flex items-center gap-2 text-base font-black text-red-300"><AlertTriangle size={18}/> Red Flags</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Hyperkalemia + ECG changes → calcium gluconate STAT.</li><li>• Anuria → urinary obstruction until proven otherwise.</li><li>• Hyponatremia + altered mental status → impending herniation.</li><li>• Severe metabolic acidosis (pH &lt;7.1) → consider bicarbonate + treat cause.</li></ul></GlassCard>)},
{id:'nextstep',label:'Best Next Step',content:(<GlassCard><h3 className="text-sm font-black text-white">Hyperkalemia Protocol</h3><p className="mt-2 text-sm leading-7 text-slate-400">1. If ECG changes: calcium gluconate 10% 10 mL IV.<br />2. Shift K+: insulin 10U + D50W, salbutamol nebulized.<br />3. Eliminate K+: furosemide, dialysis (if renal failure).<br />4. Stop K+ sources: IV fluids without K+, review medications.</p></GlassCard>)},
{id:'traps',label:'Exam Traps',content:(<GlassCard><h2 className="flex items-center gap-2 text-base font-black text-white"><Zap size={18} className="text-amber-400"/> Common Exam Traps</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Giving insulin+glucose before calcium in hyperkalemia with ECG changes.</li><li>• Correcting chronic hyponatremia too fast → irreversible brain damage.</li><li>• Using Lactated Ringer in hyperkalemia (contains K+).</li></ul></GlassCard>)},
{id:'arabic',label:'Arabic / عربي',content:(<GlassCard className="border-cyan-500/15 bg-cyan-500/3"><h2 className="flex items-center gap-2 text-base font-black text-cyan-300"><Lightbulb size={18}/> Arabic Explanation</h2><p className="mt-3 text-sm leading-8 text-slate-400">بوتاسيوم عالي + تغيرات تخطيط = غلوكونات الكالسيوم أولًا لحماية القلب. صوديوم منخفض = صحّح ببطء (أقصى 12 ملي خلال 24 ساعة). لا تستعمل رينجر لاكتيت في البوتاسيوم العالي.</p></GlassCard>)},
{id:'related',label:'Related',content:(<div className="text-center"><p className="text-xs font-bold text-slate-500">Related:</p><div className="mt-2 flex flex-wrap justify-center gap-2"><Link href="/interns/study/internal-medicine/emergency-cardiology" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Emergency Cardiology</Link><Link href="/interns/study/internal-medicine/endocrine-emergencies" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Endocrine Emergencies</Link></div></div>)},
];
export default function NephrologyPage(){return(<InternalPage title="Nephrology & Electrolytes" subtitle="الكلى والأملاح في الامتياز" introText="AKI, CKD emergencies, hyperkalemia, hyponatremia, and acid-base disorders. Focus on ECG recognition and safe correction." backHref="/interns/study/internal-medicine" backLabel="Internal Medicine"><TopicSectionPager sections={sections}/></InternalPage>);}
