import Link from 'next/link';import { InternalPage, GlassCard } from '@/components/InternalPage';import { TopicSectionPager } from '@/components/interns/TopicSectionPager';import { AlertTriangle, Zap, Lightbulb } from 'lucide-react';
const sections=[
{id:'overview',label:'Overview / لمحة',content:(<GlassCard><h2 className="text-base font-black text-white">Postpartum Hemorrhage</h2><p className="mt-2 text-sm leading-7 text-slate-400">The leading cause of maternal mortality worldwide. Interns must recognize PPH early, identify the cause (4 Ts), and initiate emergency management. Every minute counts.</p></GlassCard>)},
{id:'recognition',label:'Key Recognition',content:(<div className="grid gap-4 sm:grid-cols-2"><GlassCard><h3 className="text-sm font-black text-white">Definition</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Blood loss &gt;500 mL vaginal delivery, &gt;1000 mL C-section.</li><li>• Or any blood loss causing hemodynamic instability.</li><li>• Primary PPH: within 24h of delivery (most common).</li><li>• Secondary PPH: 24h – 6 weeks postpartum.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">4 Ts of PPH</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Tone: uterine atony (most common cause — 70%).</li><li>• Trauma: cervical/vaginal/perineal lacerations, uterine rupture.</li><li>• Tissue: retained placenta or membranes.</li><li>• Thrombin: coagulopathy (DIC, pre-existing, acquired).</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Management Steps</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• ABCDE, 2 large-bore IVs, crossmatch, activate MTP if needed.</li><li>• Uterine massage (bimanual compression).</li><li>• Oxytocin (first-line). Consider ergometrine, carboprost, misoprostol.</li><li>• Tranexamic acid 1g IV.</li></ul></GlassCard></div>)},
{id:'redflags',label:'Red Flags',content:(<GlassCard className="border-red-500/10 bg-red-500/3"><h2 className="flex items-center gap-2 text-base font-black text-red-300"><AlertTriangle size={18}/> Red Flags</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Estimated blood loss &gt;1000 mL + ongoing → activate MTP, prepare for OR.</li><li>• Soft, boggy uterus + heavy bleeding → uterine atony, bimanual compression now.</li><li>• PPH unresponsive to uterotonics → retained products or coagulopathy, surgical intervention.</li></ul></GlassCard>)},
{id:'nextstep',label:'Best Next Step',content:(<GlassCard><h3 className="text-sm font-black text-white">PPH Emergency Protocol</h3><p className="mt-2 text-sm leading-7 text-slate-400">1. Call for help — this is an emergency.<br />2. ABCDE + 2 large-bore IVs + fluids.<br />3. Uterine massage + empty bladder.<br />4. Oxytocin 5 IU slow IV → 40 IU infusion.<br />5. If no response: ergometrine, carboprost, tranexamic acid.<br />6. Surgical: Bakri balloon, B-Lynch suture, hysterectomy if needed.</p></GlassCard>)},
{id:'traps',label:'Exam Traps',content:(<GlassCard><h2 className="flex items-center gap-2 text-base font-black text-white"><Zap size={18} className="text-amber-400"/> Common Exam Traps</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Underestimating blood loss (visual estimation often half of actual).</li><li>• Not giving tranexamic acid within 3h of delivery.</li><li>• Missing retained products as a cause of secondary PPH.</li></ul></GlassCard>)},
{id:'arabic',label:'Arabic / عربي',content:(<GlassCard className="border-cyan-500/15 bg-cyan-500/3"><h2 className="flex items-center gap-2 text-base font-black text-cyan-300"><Lightbulb size={18}/> Arabic Explanation</h2><p className="mt-3 text-sm leading-8 text-slate-400">نزيف ما بعد الولادة = أكثر من 500 مل ولادة طبيعية، أو أكثر من 1000 مل قيصرية. الأسباب الأربعة (4 Ts): ارتخاء الرحم (الأكثر شيوعًا)، تمزقات، أنسجة محتبسة، اضطراب تخثر. العلاج: تدليك الرحم + أوكسيتوسين + ترانيكساميك أسيد. لا تقلل من كمية النزف.</p></GlassCard>)},
{id:'related',label:'Related',content:(<div className="text-center"><p className="text-xs font-bold text-slate-500">Related:</p><div className="mt-2 flex flex-wrap justify-center gap-2"><Link href="/interns/study/obgyn/labor-delivery" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Labor & Delivery</Link><Link href="/interns/study/surgery/fluids-electrolytes-transfusion" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Fluids & Transfusion</Link></div></div>)},
];
export default function PPHPage(){return(<InternalPage title="Postpartum Hemorrhage" subtitle="نزيف ما بعد الولادة" introText="The leading cause of maternal mortality. 4 Ts, emergency protocol, and life-saving interventions." backHref="/interns/study/obgyn" backLabel="OB/GYN"><TopicSectionPager sections={sections}/></InternalPage>);}
