import Link from 'next/link';import { InternalPage, GlassCard } from '@/components/InternalPage';import { TopicSectionPager } from '@/components/interns/TopicSectionPager';import { AlertTriangle, Zap, Lightbulb } from 'lucide-react';
const sections=[
{id:'overview',label:'Overview / لمحة',content:(<GlassCard><h2 className="text-base font-black text-white">Pediatric Red Flags</h2><p className="mt-2 text-sm leading-7 text-slate-400">Danger signs, child protection red flags, age-adjusted vitals, and developmental alerts — interns must recognize when a child is seriously unwell or at risk. These are high-yield exam topics.</p></GlassCard>)},
{id:'recognition',label:'Key Recognition',content:(<div className="grid gap-4 sm:grid-cols-2"><GlassCard><h3 className="text-sm font-black text-white">Pediatric Danger Signs (WHO)</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Unable to drink or breastfeed.</li><li>• Vomits everything.</li><li>• Convulsions (current or recent).</li><li>• Lethargic or unconscious.</li><li>• Chest indrawing or stridor at rest.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Age-Adjusted Vitals</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• HR newborn: 120-160, infant: 100-150, child: 80-120.</li><li>• RR newborn: 40-60, infant: 30-40, child: 20-30.</li><li>• SBP: &lt;1yr ~70, 1-10yr ~70+(age×2).</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Developmental Red Flags</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• No smiling at 2 months. No head support at 4 months.</li><li>• No sitting at 9 months. No walking at 18 months.</li><li>• No pointing at 18 months (autism red flag).</li><li>• No 2-word sentences at 2 years.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Child Protection Red Flags</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Multiple injuries at different sites/different stages of healing.</li><li>• Injuries inconsistent with developmental stage.</li><li>• Delay in seeking care. Inconsistent history.</li><li>• Bruises: bilateral, symmetric, or geometric patterns.</li></ul></GlassCard></div>)},
{id:'redflags',label:'Immediate Action',content:(<GlassCard className="border-red-500/10 bg-red-500/3"><h2 className="flex items-center gap-2 text-base font-black text-red-300"><AlertTriangle size={18}/> When to Escalate Immediately</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Any WHO danger sign → urgent assessment and likely admission.</li><li>• Suspected non-accidental injury → document, involve seniors, notify child protection.</li><li>• Capillary refill &gt;2s + abnormal vitals → compensated shock, act now.</li></ul></GlassCard>)},
{id:'nextstep',label:'Best Next Step',content:(<GlassCard><h3 className="text-sm font-black text-white">Pediatric Assessment Triangle</h3><p className="mt-2 text-sm leading-7 text-slate-400">1. Appearance: tone, interaction, consolability, look/gaze, cry.<br />2. Work of breathing: abnormal sounds, positioning, retractions, nasal flaring.<br />3. Circulation: pallor, mottling, cyanosis.<br />Abnormal in any arm → immediate intervention.</p></GlassCard>)},
{id:'traps',label:'Exam Traps',content:(<GlassCard><h2 className="flex items-center gap-2 text-base font-black text-white"><Zap size={18} className="text-amber-400"/> Common Exam Traps</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Relying on adult vital sign norms for children.</li><li>• Missing non-accidental injury in a plausible-sounding history.</li><li>• Not checking developmental milestones in any well-child visit.</li></ul></GlassCard>)},
{id:'arabic',label:'Arabic / عربي',content:(<GlassCard className="border-cyan-500/15 bg-cyan-500/3"><h2 className="flex items-center gap-2 text-base font-black text-cyan-300"><Lightbulb size={18}/> Arabic Explanation</h2><p className="mt-3 text-sm leading-8 text-slate-400">علامات الخطر عند الأطفال (WHO): لا يستطيع الشرب، يتقيأ كل شيء، تشنجات، خامل أو فاقد وعي، انسحاب صدري. علامات إساءة معاملة الطفل: كدمات متعددة في مواقع مختلفة بمراحل شفاء مختلفة — سجّل وأبلغ.</p></GlassCard>)},
{id:'related',label:'Related',content:(<div className="text-center"><p className="text-xs font-bold text-slate-500">Related:</p><div className="mt-2 flex flex-wrap justify-center gap-2"><Link href="/interns/study/pediatrics/neonatal-emergencies" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Neonatal Emergencies</Link><Link href="/red-flags-ddx" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Red Flags & DDX</Link></div></div>)},
];
export default function PedsRedFlagsPage(){return(<InternalPage title="Pediatric Red Flags" subtitle="العلامات الحمراء عند الأطفال" introText="WHO danger signs, child protection, age-adjusted vitals, and developmental red flags. Must-know for every intern." backHref="/interns/study/pediatrics" backLabel="Pediatrics"><TopicSectionPager sections={sections}/></InternalPage>);}
