import Link from 'next/link';import { InternalPage, GlassCard } from '@/components/InternalPage';import { TopicSectionPager } from '@/components/interns/TopicSectionPager';import { AlertTriangle, Zap, Lightbulb } from 'lucide-react';
const sections=[
{id:'overview',label:'Overview / لمحة',content:(<GlassCard><h2 className="text-base font-black text-white">Wounds & Surgical Infections</h2><p className="mt-2 text-sm leading-7 text-slate-400">Wound healing, wound infection, abscess, antibiotics, and postoperative fever — common surgical problems every intern manages. Understanding wound classification helps guide antibiotic use.</p></GlassCard>)},
{id:'recognition',label:'Key Recognition',content:(<div className="grid gap-4 sm:grid-cols-2"><GlassCard><h3 className="text-sm font-black text-white">Wound Healing</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Phases: hemostasis → inflammation → proliferation → remodeling.</li><li>• Primary intention: clean wound edges approximated.</li><li>• Secondary: left open to heal by granulation.</li><li>• Tertiary (delayed primary): closed after 3-5 days.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Wound Classification</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Clean: no entry into GI/GU/respiratory tracts.</li><li>• Clean-contaminated: controlled entry into a tract.</li><li>• Contaminated: gross spillage, open fracture.</li><li>• Dirty: established infection, perforation.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Surgical Site Infection</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Erythema, warmth, purulent drainage, dehiscence.</li><li>• Treatment: open wound, drain abscess, antibiotics.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Postoperative Fever</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• 5 Ws: Wind (atelectasis day 1-2), Water (UTI), Wound (day 3-5), Walking (DVT), Wonder drugs (drug fever).</li><li>• Most fever in first 48h is non-infectious (atelectasis).</li></ul></GlassCard></div>)},
{id:'redflags',label:'Red Flags',content:(<GlassCard className="border-red-500/10 bg-red-500/3"><h2 className="flex items-center gap-2 text-base font-black text-red-300"><AlertTriangle size={18}/> Red Flags</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Wound dehiscence with bowel visible → evisceration, cover with saline gauze, OR.</li><li>• Crepitus in wound → gas gangrene (C. perfringens), surgical emergency.</li><li>• Necrotizing fasciitis: pain out of proportion, rapid spread → debridement STAT.</li></ul></GlassCard>)},
{id:'nextstep',label:'Best Next Step',content:(<GlassCard><h3 className="text-sm font-black text-white">Abscess Management</h3><p className="mt-2 text-sm leading-7 text-slate-400">1. Incision and drainage — antibiotics alone are insufficient.<br />2. Culture purulent material.<br />3. Pack wound, allow secondary healing.<br />4. Antibiotics if: surrounding cellulitis, immunocompromised, systemic signs.</p></GlassCard>)},
{id:'traps',label:'Exam Traps',content:(<GlassCard><h2 className="flex items-center gap-2 text-base font-black text-white"><Zap size={18} className="text-amber-400"/> Common Exam Traps</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Treating an abscess with antibiotics alone — always drain.</li><li>• Missing necrotizing fasciitis (pain out of proportion is the clue).</li><li>• Assuming all post-op fever is infection in the first 48h.</li></ul></GlassCard>)},
{id:'arabic',label:'Arabic / عربي',content:(<GlassCard className="border-cyan-500/15 bg-cyan-500/3"><h2 className="flex items-center gap-2 text-base font-black text-cyan-300"><Lightbulb size={18}/> Arabic Explanation</h2><p className="mt-3 text-sm leading-8 text-slate-400">الخراج: فتح وتصريف — المضاد الحيوي وحده لا يكفي. التهاب اللفافة الناخر: ألم شديد لا يتناسب مع العلامات = حالة طارئة. حرارة بعد العملية في أول 48 ساعة غالبًا انخماص رئوي، ليس التهابًا.</p></GlassCard>)},
{id:'related',label:'Related',content:(<div className="text-center"><p className="text-xs font-bold text-slate-500">Related:</p><div className="mt-2 flex flex-wrap justify-center gap-2"><Link href="/interns/study/surgery/surgical-basics" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Surgical Basics</Link><Link href="/interns/study/internal-medicine/infectious-disease" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Infectious Disease</Link></div></div>)},
];
export default function WoundsPage(){return(<InternalPage title="Wounds & Infections" subtitle="الجروح والالتهابات الجراحية" introText="Wound healing, classification, SSI, abscess, and postoperative fever. Practical surgical knowledge for every intern." backHref="/interns/study/surgery" backLabel="Surgery"><TopicSectionPager sections={sections}/></InternalPage>);}
