import Link from 'next/link';import { InternalPage, GlassCard } from '@/components/InternalPage';import { TopicSectionPager } from '@/components/interns/TopicSectionPager';import { AlertTriangle, Zap, Lightbulb } from 'lucide-react';
const sections=[
{id:'overview',label:'Overview / لمحة',content:(<GlassCard><h2 className="text-base font-black text-white">Pediatric Infectious Disease & Vaccines</h2><p className="mt-2 text-sm leading-7 text-slate-400">Fever, rash illnesses, meningitis, sepsis, and the Jordanian vaccination schedule — heavily tested in internship exams. Know the vaccine schedule and common infectious presentations.</p></GlassCard>)},
{id:'recognition',label:'Key Recognition',content:(<div className="grid gap-4 sm:grid-cols-2"><GlassCard><h3 className="text-sm font-black text-white">Fever Without Source</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Neonate (&lt;28 days): full septic workup + admit + IV antibiotics.</li><li>• 1-3 months: risk-stratify (Rochester criteria).</li><li>• &gt;3 months: assess clinically, treat source if found.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Jordanian Vaccination Schedule</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• BCG: at birth. IPV+DTaP+Hib+HepB: 2,3,4 months.</li><li>• Rotavirus: 2,3,4 months (oral). OPV: 4,9,18 months.</li><li>• Measles: 9 months. MMR: 12 months. HepA: 12,18 months.</li><li>• DTP booster: 18 months. Td: 15 years.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Vaccine Types</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Live attenuated: MMR, OPV, BCG, rotavirus, varicella, yellow fever.</li><li>• Killed/inactivated: IPV, HepA, HepB, injectable influenza.</li><li>• Toxoid: diphtheria, tetanus.</li><li>• Conjugate: Hib, pneumococcal, meningococcal.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Rash Illnesses</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Measles: fever + cough + coryza + conjunctivitis + Koplik spots → maculopapular rash.</li><li>• Rubella: mild fever + lymphadenopathy → rash.</li><li>• Varicella: vesicular rash, different stages.</li></ul></GlassCard></div>)},
{id:'redflags',label:'Red Flags',content:(<GlassCard className="border-red-500/10 bg-red-500/3"><h2 className="flex items-center gap-2 text-base font-black text-red-300"><AlertTriangle size={18}/> Red Flags</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Petechial/purpuric rash + fever → meningococcemia, antibiotics STAT.</li><li>• Neonatal fever &lt;28 days → always admit, full workup, IV antibiotics.</li><li>• Febrile seizure + meningeal signs → LP for meningitis.</li></ul></GlassCard>)},
{id:'nextstep',label:'Best Next Step',content:(<GlassCard><h3 className="text-sm font-black text-white">Vaccine Storage Rules</h3><p className="mt-2 text-sm leading-7 text-slate-400">• Store at 2-8°C (refrigerator). BCG most heat stable. OPV most heat sensitive.<br />• Varicella and MMR can be frozen. Hepatitis B is most freeze-sensitive.<br />• Cold chain: maintain from manufacture to administration point.</p></GlassCard>)},
{id:'traps',label:'Exam Traps',content:(<GlassCard><h2 className="flex items-center gap-2 text-base font-black text-white"><Zap size={18} className="text-amber-400"/> Common Exam Traps</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Pneumococcal conjugate vaccine is NOT in Jordanian schedule (exam favorite).</li><li>• MMR is given subcutaneously, not IM.</li><li>• Contraindications to breastfeeding: HIV (in developed countries), HTLV-1, galactosemia — NOT HepA, HepC, or CMV.</li></ul></GlassCard>)},
{id:'arabic',label:'Arabic / عربي',content:(<GlassCard className="border-cyan-500/15 bg-cyan-500/3"><h2 className="flex items-center gap-2 text-base font-black text-cyan-300"><Lightbulb size={18}/> Arabic Explanation</h2><p className="mt-3 text-sm leading-8 text-slate-400">اللقاحات الحية المضعفة: MMR، OPV، BCG، الروتا، الجديري. برنامج التطعيم الأردني: لا يشمل المكورات الرئوية (pneumococcal) — سؤال امتحاني شائع. حرارة المولود أقل من 28 يوم = تنويم + مضادات حيوية وريدية دائمًا.</p></GlassCard>)},
{id:'related',label:'Related',content:(<div className="text-center"><p className="text-xs font-bold text-slate-500">Related:</p><div className="mt-2 flex flex-wrap justify-center gap-2"><Link href="/interns/study/pediatrics/neonatal-emergencies" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Neonatal Emergencies</Link><Link href="/interns/study/internal-medicine/infectious-disease" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Adult ID Emergencies</Link></div></div>)},
];
export default function PedsIDPage(){return(<InternalPage title="Pediatric ID & Vaccines" subtitle="الأمراض المعدية والتطعيمات عند الأطفال" introText="Fever, rash, meningitis, sepsis, and the Jordanian vaccination schedule. Heavily tested in internship exams." backHref="/interns/study/pediatrics" backLabel="Pediatrics"><TopicSectionPager sections={sections}/></InternalPage>);}
