import Link from 'next/link';import { InternalPage, GlassCard } from '@/components/InternalPage';import { TopicSectionPager } from '@/components/interns/TopicSectionPager';import { AlertTriangle, Zap, Lightbulb } from 'lucide-react';
const sections=[
{id:'overview',label:'Overview / لمحة',content:(<GlassCard><h2 className="text-base font-black text-white">Pediatric Respiratory Emergencies</h2><p className="mt-2 text-sm leading-7 text-slate-400">Croup, bronchiolitis, asthma, pneumonia, and foreign body aspiration — respiratory distress is the most common pediatric emergency. Interns must recognize severity and act quickly.</p></GlassCard>)},
{id:'recognition',label:'Key Recognition',content:(<div className="grid gap-4 sm:grid-cols-2"><GlassCard><h3 className="text-sm font-black text-white">Croup</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Parainfluenza virus. Barking cough, inspiratory stridor.</li><li>• Age: 6 months – 3 years. Low-grade fever.</li><li>• Treatment: dexamethasone + nebulized epinephrine.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Bronchiolitis</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• RSV most common. Wheezing, tachypnea, retractions.</li><li>• Age: &lt;2 years. May have low-grade or no fever.</li><li>• Treatment: supportive (O2, fluids). No routine bronchodilators.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Foreign Body Aspiration</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Sudden choking, unilateral wheeze, asymmetric breath sounds.</li><li>• Most common: 1-3 years, peanuts/seeds.</li><li>• Treatment: rigid bronchoscopy (urgent).</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Epiglottitis</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• High fever, drooling, stridor, tripod position.</li><li>• Do NOT examine throat — may precipitate obstruction.</li><li>• Secure airway in OR. Then ceftriaxone + vancomycin.</li></ul></GlassCard></div>)},
{id:'redflags',label:'Red Flags',content:(<GlassCard className="border-red-500/10 bg-red-500/3"><h2 className="flex items-center gap-2 text-base font-black text-red-300"><AlertTriangle size={18}/> Red Flags</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Stridor at rest → severe croup, needs epinephrine + observation.</li><li>• Drooling + stridor + high fever → epiglottitis, secure airway first.</li><li>• Unilateral wheeze after choking → foreign body, rigid bronchoscopy.</li><li>• Silent chest in asthma → life-threatening, imminent respiratory arrest.</li></ul></GlassCard>)},
{id:'nextstep',label:'Best Next Step',content:(<GlassCard><h3 className="text-sm font-black text-white">Croup Severity & Management</h3><p className="mt-2 text-sm leading-7 text-slate-400">Mild (barking cough at rest): oral dexamethasone 0.15 mg/kg.<br />Moderate (stridor at rest): dexamethasone + nebulized epinephrine.<br />Severe (stridor + retractions + agitation): admit, repeat epinephrine, monitor.</p></GlassCard>)},
{id:'traps',label:'Exam Traps',content:(<GlassCard><h2 className="flex items-center gap-2 text-base font-black text-white"><Zap size={18} className="text-amber-400"/> Common Exam Traps</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Examining the throat in suspected epiglottitis.</li><li>• Using antibiotics for bronchiolitis (viral).</li><li>• Not considering foreign body in unilateral wheeze.</li></ul></GlassCard>)},
{id:'arabic',label:'Arabic / عربي',content:(<GlassCard className="border-cyan-500/15 bg-cyan-500/3"><h2 className="flex items-center gap-2 text-base font-black text-cyan-300"><Lightbulb size={18}/> Arabic Explanation</h2><p className="mt-3 text-sm leading-8 text-slate-400">الخانوق (croup): سعال نباحي + صرير شهيقي. العلاج: ديكساميثازون + أدرينالين مرذذ. التهاب لسان المزمار: حرارة عالية + سيلان لعاب + صرير = لا تفحص الحلق! أمّن المجرى التنفسي أولًا. التهاب القصيبات (RSV): دعم بالأوكسجين والسوائل فقط.</p></GlassCard>)},
{id:'related',label:'Related',content:(<div className="text-center"><p className="text-xs font-bold text-slate-500">Related:</p><div className="mt-2 flex flex-wrap justify-center gap-2"><Link href="/interns/study/pediatrics/neonatal-emergencies" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Neonatal Emergencies</Link><Link href="/interns/study/pediatrics/infectious-disease-vaccines" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Infectious Disease</Link></div></div>)},
];
export default function PedsRespPage(){return(<InternalPage title="Pediatric Respiratory Emergencies" subtitle="طوارئ التنفس عند الأطفال" introText="Croup, bronchiolitis, asthma, pneumonia, and foreign body aspiration. Focus on severity recognition and specific treatment." backHref="/interns/study/pediatrics" backLabel="Pediatrics"><TopicSectionPager sections={sections}/></InternalPage>);}
