import Link from 'next/link';import { InternalPage, GlassCard } from '@/components/InternalPage';import { TopicSectionPager } from '@/components/interns/TopicSectionPager';import { AlertTriangle, Zap, Lightbulb } from 'lucide-react';
const sections=[
{id:'overview',label:'Overview / لمحة',content:(<GlassCard><h2 className="text-base font-black text-white">Gynecologic Emergencies</h2><p className="mt-2 text-sm leading-7 text-slate-400">Ovarian torsion, PID, acute pelvic pain, and gynecologic red flags — interns must recognize these in the ED and differentiate from surgical and obstetric emergencies.</p></GlassCard>)},
{id:'recognition',label:'Key Recognition',content:(<div className="grid gap-4 sm:grid-cols-2"><GlassCard><h3 className="text-sm font-black text-white">Ovarian Torsion</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Sudden severe unilateral pelvic pain, often with nausea/vomiting.</li><li>• Adnexal mass on exam. Risk: ovarian cyst/tumor.</li><li>• Doppler US: absent arterial/venous flow.</li><li>• Surgical emergency — detorsion within 6-8h to save ovary.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Pelvic Inflammatory Disease</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Lower abdominal pain, cervical motion tenderness, adnexal tenderness.</li><li>• Chlamydia and gonorrhea most common. Can cause tubo-ovarian abscess.</li><li>• Treatment: ceftriaxone + doxycycline + metronidazole.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Acute Pelvic Pain</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Always rule out pregnancy first.</li><li>• Differential: ectopic, torsion, PID, ruptured cyst, appendicitis.</li><li>• Pelvic US + pregnancy test are first-line investigations.</li></ul></GlassCard></div>)},
{id:'redflags',label:'Red Flags',content:(<GlassCard className="border-red-500/10 bg-red-500/3"><h2 className="flex items-center gap-2 text-base font-black text-red-300"><AlertTriangle size={18}/> Red Flags</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Sudden severe unilateral pain + adnexal mass → ovarian torsion, urgent surgery.</li><li>• Fever + pelvic pain + cervical motion tenderness → PID, antibiotics + ?admit.</li><li>• Tubo-ovarian abscess → admit, IV antibiotics, possible drainage.</li></ul></GlassCard>)},
{id:'nextstep',label:'Best Next Step',content:(<GlassCard><h3 className="text-sm font-black text-white">Acute Pelvic Pain Workup</h3><p className="mt-2 text-sm leading-7 text-slate-400">1. Pregnancy test (stat) — rule out ectopic.<br />2. Pelvic ultrasound (transvaginal) — assess ovaries, adnexa, uterus.<br />3. CBC, CRP, urinalysis.<br />4. Surgical consult if torsion, abscess, or ectopic suspected.</p></GlassCard>)},
{id:'traps',label:'Exam Traps',content:(<GlassCard><h2 className="flex items-center gap-2 text-base font-black text-white"><Zap size={18} className="text-amber-400"/> Common Exam Traps</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Missing ovarian torsion in a young patient with acute pelvic pain.</li><li>• Treating PID without covering Chlamydia (doxycycline essential).</li><li>• Not considering appendicitis in RLQ pain (overlap with gynecologic causes).</li></ul></GlassCard>)},
{id:'arabic',label:'Arabic / عربي',content:(<GlassCard className="border-cyan-500/15 bg-cyan-500/3"><h2 className="flex items-center gap-2 text-base font-black text-cyan-300"><Lightbulb size={18}/> Arabic Explanation</h2><p className="mt-3 text-sm leading-8 text-slate-400">ألم الحوض الحاد: اختبار الحمل أولًا دائمًا. التواء المبيض: ألم مفاجئ شديد في جهة واحدة + كتلة ملحقات = عملية خلال 6-8 ساعات. مرض التهاب الحوض: سيفترياكسون + دوكسيسايكلين + ميترونيدازول.</p></GlassCard>)},
{id:'related',label:'Related',content:(<div className="text-center"><p className="text-xs font-bold text-slate-500">Related:</p><div className="mt-2 flex flex-wrap justify-center gap-2"><Link href="/interns/study/obgyn/ectopic-pregnancy" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Ectopic Pregnancy</Link><Link href="/interns/study/surgery/acute-abdomen" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Acute Abdomen</Link></div></div>)},
];
export default function GyneEmergPage(){return(<InternalPage title="Gynecologic Emergencies" subtitle="طوارئ أمراض النساء" introText="Ovarian torsion, PID, acute pelvic pain, and gynecologic red flags. Differentiate from surgical and obstetric causes." backHref="/interns/study/obgyn" backLabel="OB/GYN"><TopicSectionPager sections={sections}/></InternalPage>);}
