import Link from 'next/link';import { InternalPage, GlassCard } from '@/components/InternalPage';import { TopicSectionPager } from '@/components/interns/TopicSectionPager';import { AlertTriangle, Zap, Lightbulb } from 'lucide-react';
const sections=[
{id:'overview',label:'Overview / لمحة',content:(<GlassCard><h2 className="text-base font-black text-white">GI Emergencies</h2><p className="mt-2 text-sm leading-7 text-slate-400">GI bleeding, liver failure, pancreatitis, and bowel obstruction — common ED presentations where interns must assess severity and initiate management. GI bleeding is one of the most tested topics.</p></GlassCard>)},
{id:'recognition',label:'Key Recognition',content:(<div className="grid gap-4 sm:grid-cols-2"><GlassCard><h3 className="text-sm font-black text-white">Upper GI Bleed</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Hematemesis, melena. Glasgow-Blatchford score for risk.</li><li>• ABCD, large-bore IVs, PPI infusion, octreotide if varices.</li><li>• Urgent endoscopy within 24h (sooner if unstable).</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Pancreatitis</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Epigastric pain radiating to back, amylase/lipase &gt;3× normal.</li><li>• Gallstones and alcohol are the most common causes.</li><li>• Treatment: aggressive IV fluids, NPO, analgesia, treat cause.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Liver Failure</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Jaundice, ascites, encephalopathy, coagulopathy.</li><li>• Precipitants: infection, GI bleed, constipation, drugs, alcohol.</li><li>• Lactulose for encephalopathy. Terlipressin + albumin for hepatorenal.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Bowel Obstruction</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Colicky pain, distension, vomiting, obstipation.</li><li>• X-ray: dilated loops, air-fluid levels.</li><li>• Management: NPO, NG tube, IV fluids, surgical consult.</li></ul></GlassCard></div>)},
{id:'redflags',label:'Red Flags',content:(<GlassCard className="border-red-500/10 bg-red-500/3"><h2 className="flex items-center gap-2 text-base font-black text-red-300"><AlertTriangle size={18}/> Red Flags</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Hematemesis + hypotension → massive UGIB, urgent scope.</li><li>• Severe epigastric pain + hypotension → hemorrhagic pancreatitis.</li><li>• Altered mental status + jaundice → hepatic encephalopathy.</li><li>• Rigid abdomen + hypotension → perforated viscus.</li></ul></GlassCard>)},
{id:'nextstep',label:'Best Next Step',content:(<GlassCard><h3 className="text-sm font-black text-white">Upper GI Bleed Protocol</h3><p className="mt-2 text-sm leading-7 text-slate-400">1. ABCDE, 2 large-bore IVs, crossmatch.<br />2. IV PPI (pantoprazole 80 mg bolus + infusion).<br />3. If varices suspected: octreotide/terlipressin + antibiotics.<br />4. Transfusion: target Hb &gt;7 (restrictive strategy).<br />5. Risk-stratify and arrange endoscopy.</p></GlassCard>)},
{id:'traps',label:'Exam Traps',content:(<GlassCard><h2 className="flex items-center gap-2 text-base font-black text-white"><Zap size={18} className="text-amber-400"/> Common Exam Traps</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Missing variceal bleed in a patient with known liver disease.</li><li>• Not giving antibiotics in variceal bleeding (reduces mortality).</li><li>• Over-transfusing UGIB (Hb target &gt;7, not &gt;10).</li></ul></GlassCard>)},
{id:'arabic',label:'Arabic / عربي',content:(<GlassCard className="border-cyan-500/15 bg-cyan-500/3"><h2 className="flex items-center gap-2 text-base font-black text-cyan-300"><Lightbulb size={18}/> Arabic Explanation</h2><p className="mt-3 text-sm leading-8 text-slate-400">نزيف الجهاز الهضمي العلوي: كانيولتين عريضتين + PPI وريدي + أكتريوتايد إذا دوالي. لا تزيد الهيموجلوبين فوق 7-8 بدون داعٍ. التهاب البنكرياس: سوائل مكثفة وريدية + مسكنات + لا شيء بالفم.</p></GlassCard>)},
{id:'related',label:'Related',content:(<div className="text-center"><p className="text-xs font-bold text-slate-500">Related:</p><div className="mt-2 flex flex-wrap justify-center gap-2"><Link href="/interns/study/surgery/acute-abdomen" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Acute Abdomen</Link><Link href="/interns/study/internal-medicine/nephrology-electrolytes" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Nephrology</Link></div></div>)},
];
export default function GIPage(){return(<InternalPage title="GI Emergencies" subtitle="طوارئ الجهاز الهضمي في الامتياز" introText="GI bleeding, liver failure, pancreatitis, and bowel obstruction. Focus on severity assessment and initial management." backHref="/interns/study/internal-medicine" backLabel="Internal Medicine"><TopicSectionPager sections={sections}/></InternalPage>);}
