import Link from 'next/link';import { InternalPage, GlassCard } from '@/components/InternalPage';import { TopicSectionPager } from '@/components/interns/TopicSectionPager';import { AlertTriangle, Zap, Lightbulb } from 'lucide-react';
const sections=[
{id:'overview',label:'Overview / لمحة',content:(<GlassCard><h2 className="text-base font-black text-white">Vascular & Urology Emergencies</h2><p className="mt-2 text-sm leading-7 text-slate-400">DVT, acute limb ischemia, AAA, urinary retention, testicular torsion, and hematuria — interns must recognize these quickly. Missing limb ischemia or torsion can have devastating consequences.</p></GlassCard>)},
{id:'recognition',label:'Key Recognition',content:(<div className="grid gap-4 sm:grid-cols-2"><GlassCard><h3 className="text-sm font-black text-white">DVT</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Calf swelling, pain, erythema. Well criteria for pre-test probability.</li><li>• D-dimer if low probability. Doppler US confirms.</li><li>• Treatment: LMWH → warfarin or DOAC.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Acute Limb Ischemia</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• 6 Ps: Pain, pallor, pulselessness, paresthesia, paralysis, poikilothermia.</li><li>• Surgical emergency — vascular consult immediately.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">AAA</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Elderly male + back/flank pain + hypotension → ruptured AAA.</li><li>• Bedside ultrasound. Urgent vascular surgery.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Urology Emergencies</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Testicular torsion: sudden severe pain, abnormal lie, absent cremasteric reflex.</li><li>• Urinary retention: painful, palpable bladder → catheterize.</li><li>• Renal colic: flank pain radiating to groin → CT KUB, NSAIDs.</li></ul></GlassCard></div>)},
{id:'redflags',label:'Red Flags',content:(<GlassCard className="border-red-500/10 bg-red-500/3"><h2 className="flex items-center gap-2 text-base font-black text-red-300"><AlertTriangle size={18}/> Red Flags</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• 6 Ps + sudden onset → acute limb ischemia, revascularize within 6h.</li><li>• Hypotension + pulsatile abdominal mass → ruptured AAA.</li><li>• Acute testicular pain + absent cremasteric → torsion, surgery within 6h.</li></ul></GlassCard>)},
{id:'nextstep',label:'Best Next Step',content:(<GlassCard><h3 className="text-sm font-black text-white">Suspected AAA Protocol</h3><p className="mt-2 text-sm leading-7 text-slate-400">1. ABCDE, 2 large-bore IVs, crossmatch 6 units.<br />2. Bedside ultrasound — measure aortic diameter.<br />3. If ruptured: permissive hypotension (SBP 80-90), OR immediately.<br />4. Do NOT delay for CT if unstable.</p></GlassCard>)},
{id:'traps',label:'Exam Traps',content:(<GlassCard><h2 className="flex items-center gap-2 text-base font-black text-white"><Zap size={18} className="text-amber-400"/> Common Exam Traps</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Missing AAA in elderly male with renal colic-like symptoms.</li><li>• Not considering testicular torsion in any acute scrotal pain.</li><li>• Forgetting DVT prophylaxis in immobilized patients.</li></ul></GlassCard>)},
{id:'arabic',label:'Arabic / عربي',content:(<GlassCard className="border-cyan-500/15 bg-cyan-500/3"><h2 className="flex items-center gap-2 text-base font-black text-cyan-300"><Lightbulb size={18}/> Arabic Explanation</h2><p className="mt-3 text-sm leading-8 text-slate-400">رجل كبيرة بالعمر + ألم ظهر/خاصرة + هبوط ضغط = AAA متمزق حتى يثبت العكس. ألم خصية حاد + منعكس مشمومي غائب = التواء خصية = عملية خلال 6 ساعات. احتباس بولي: قسطرة. لا تنسى الوقاية من DVT في أي مريض طريح الفراش.</p></GlassCard>)},
{id:'related',label:'Related',content:(<div className="text-center"><p className="text-xs font-bold text-slate-500">Related:</p><div className="mt-2 flex flex-wrap justify-center gap-2"><Link href="/interns/study/surgery/trauma" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Trauma</Link><Link href="/interns/study/surgery/acute-abdomen" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Acute Abdomen</Link></div></div>)},
];
export default function VascularUroPage(){return(<InternalPage title="Vascular & Urology" subtitle="جراحة الأوعية والمسالك البولية" introText="DVT, acute limb ischemia, AAA, urinary retention, testicular torsion, and hematuria. Time-sensitive emergencies." backHref="/interns/study/surgery" backLabel="Surgery"><TopicSectionPager sections={sections}/></InternalPage>);}
