import Link from 'next/link';import { InternalPage, GlassCard } from '@/components/InternalPage';import { TopicSectionPager } from '@/components/interns/TopicSectionPager';import { AlertTriangle, Zap, Lightbulb } from 'lucide-react';
const sections=[
{id:'overview',label:'Overview / لمحة',content:(<GlassCard><h2 className="text-base font-black text-white">Early Pregnancy Bleeding</h2><p className="mt-2 text-sm leading-7 text-slate-400">Ectopic pregnancy, abortion types, warning signs, and first-step thinking — a high-stakes topic where missing the diagnosis can be fatal. OBGYN is ~10-15% of internship exam weight.</p><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Ectopic pregnancy is the #1 cause of first-trimester maternal death.</li><li>• Any woman of childbearing age with abdominal pain or syncope → pregnancy test.</li><li>• Abortion types are classic exam discriminators — os status is key.</li></ul></GlassCard>)},
{id:'recognition',label:'Key Recognition',content:(<div className="grid gap-4 sm:grid-cols-2"><GlassCard><h3 className="text-sm font-black text-white">Ectopic Pregnancy</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Triad: amenorrhea + vaginal bleeding + unilateral pelvic pain.</li><li>• Risk: PID, previous ectopic, tubal surgery, IUD, smoking.</li><li>• TVUS + serial β-hCG. Ruptured: hypotension, peritoneal signs.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Abortion Types</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Threatened: bleeding, closed os, viable pregnancy.</li><li>• Inevitable: bleeding, open os, products not passed.</li><li>• Incomplete: partial passage, open os, retained tissue.</li><li>• Complete: all products passed, os closed, empty uterus.</li><li>• Missed: fetal demise, os closed, no cardiac activity.</li><li>• Septic: fever, foul discharge — emergency.</li></ul></GlassCard></div>)},
{id:'redflags',label:'Red Flags',content:(<GlassCard className="border-red-500/10 bg-red-500/3"><h2 className="flex items-center gap-2 text-base font-black text-red-300"><AlertTriangle size={18}/> Red Flags</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Hypotension + positive pregnancy test + abdominal pain → ruptured ectopic.</li><li>• Syncope in reproductive-age woman → always rule out ectopic.</li><li>• Heavy bleeding + open os + products → incomplete abortion, needs evacuation.</li></ul></GlassCard>)},
{id:'nextstep',label:'Best Next Step',content:(<GlassCard><h3 className="text-sm font-black text-white">Suspected Ectopic Protocol</h3><p className="mt-2 text-sm leading-7 text-slate-400">1. ABCDE, 2 large-bore IVs if unstable.<br />2. Urine pregnancy test (stat).<br />3. If positive: transvaginal US.<br />4. Serial β-hCG if US inconclusive.<br />5. If ruptured/unstable: immediate laparoscopy/laparotomy.<br />6. Rh-negative: give Anti-D immunoglobulin.</p></GlassCard>)},
{id:'traps',label:'Exam Traps',content:(<GlassCard><h2 className="flex items-center gap-2 text-base font-black text-white"><Zap size={18} className="text-amber-400"/> Common Exam Traps</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Forgetting pregnancy test in any woman of childbearing age.</li><li>• Relying on single β-hCG — need serial levels for trend.</li><li>• Confusing abortion types — os status (open vs. closed) is the discriminator.</li></ul></GlassCard>)},
{id:'arabic',label:'Arabic / عربي',content:(<GlassCard className="border-cyan-500/15 bg-cyan-500/3"><h2 className="flex items-center gap-2 text-base font-black text-cyan-300"><Lightbulb size={18}/> Arabic Explanation</h2><p className="mt-3 text-sm leading-8 text-slate-400">أي سيدة في عمر الإنجاب + ألم بطن أو إغماء = اختبار حمل فورًا. الحمل خارج الرحم هو القاتل الأول. فحص عنق الرحم هو المفتاح للتمييز بين أنواع الإجهاض. دائماً أعطِ Anti-D إذا الزمرة سالبة.</p></GlassCard>)},
{id:'related',label:'Related',content:(<div className="text-center"><p className="text-xs font-bold text-slate-500">Related:</p><div className="mt-2 flex flex-wrap justify-center gap-2"><Link href="/interns/study/obgyn/ectopic-pregnancy" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Ectopic Pregnancy</Link><Link href="/interns/study/obgyn/hypertensive-disorders" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Hypertensive Disorders</Link></div></div>)},
];
export default function EarlyPregBleedPage(){return(<InternalPage title="Early Pregnancy Bleeding" subtitle="نزيف الحمل المبكر" introText="Ectopic pregnancy and abortion types. Focus on recognition, differentiation, and emergency management." backHref="/interns/study/obgyn" backLabel="OB/GYN"><TopicSectionPager sections={sections}/></InternalPage>);}
