import Image from 'next/image';
import { SectionFeatureHero } from '@/components/SectionFeatureHero';
import { MedicalSafetyNotice } from '@/components/MedicalSafetyNotice';
import { ProgressActions } from '@/components/ProgressActions';
import { airwayModules, oxygenInterfaces, ventilatorModes } from '@/data/intubationVentilator';

export default function IntubationVentilatorPage(){return <>
  <SectionFeatureHero title="Intubation & Ventilator / Modes in ER" subtitle="A practical ER airway and ventilator learning center adapted to Jordanian ER context, using Hamilton-G5-style visual logic and simple Arabic explanation for difficult concepts." arabic="هذا القسم يشرح الانتوبيشن والمنفسة بطريقة بسيطة: متى أحتاج الأنبوب؟ كيف أوصل الجهاز؟ ما الفرق بين المودات؟ وماذا أراقب بعد التوصيل؟" tone="blue"/>
  <MedicalSafetyNotice compact note="Ventilator settings, RSI drugs, sedation, paralysis, alarms, and post-intubation care must be verified with local ER/ICU protocol and senior supervision." arabic="إعدادات المنفسة وأدوية الانتوبيشن والتخدير والشلل يجب مراجعتها حسب بروتوكول المستشفى والطبيب المسؤول." />
  <section className="grid gap-6 lg:grid-cols-[0.9fr_1.1fr]"><div className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm"><div className="text-xs font-black uppercase tracking-wider text-blue-700">Device visual reference</div><h2 className="mt-2 text-2xl font-black text-slate-950">Hamilton-G5 style screen</h2><p className="mt-3 text-sm leading-7 text-slate-600">The uploaded Hamilton-G5 image is used as the visual reference for understanding the ventilator screen, mode selection, settings, alarms, and standby/continue logic.</p><div className="arabic-support mt-4 rounded-2xl bg-blue-50 p-4 text-sm leading-7">الصورة ليست للزينة؛ سنستخدم منطق الشاشة لفهم أين نختار المود، أين نضبط FiO₂/PEEP/RR/VT، وأين نقرأ الإنذارات.</div></div><div className="relative min-h-[340px] overflow-hidden rounded-[2rem] border border-slate-200 bg-slate-950 shadow-sm"><Image src="/reference/hamilton-g5-reference.jpeg" alt="Hamilton G5 ventilator reference" fill className="object-contain p-3" /></div></section>
  <section className="mt-8 grid gap-6">{airwayModules.map((m)=><article key={m.id} className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm"><div className="text-xs font-black uppercase tracking-wider text-emerald-700">Airway module</div><h2 className="mt-2 text-3xl font-black text-slate-950">{m.title}</h2><p className="mt-3 text-sm leading-7 text-slate-700">{m.englishCore}</p><div className="arabic-support mt-4 rounded-2xl bg-emerald-50 p-4 text-sm leading-8">{m.arabicIntro}</div><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{m.steps.map((s,idx)=><div key={s.label} className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-slate-950 text-sm font-black text-white">{idx+1}</div><h3 className="mt-3 font-black text-slate-950">{s.label}</h3><p className="mt-2 text-sm leading-6 text-slate-700"><strong>Why:</strong> {s.why}</p><p className="mt-2 rounded-xl bg-white px-3 py-2 text-xs font-black text-blue-700">Visual needed: {s.visual}</p><div className="arabic-support mt-2 text-xs leading-6">{s.arabic}</div></div>)}</div><ProgressActions id={`airway-${m.id}`} section="Intubation & Ventilator" title={m.title}/></article>)}</section>
  <section className="mt-8"><div className="mb-4"><h2 className="text-3xl font-black text-slate-950">Ventilator Modes — simple comparison</h2><p className="mt-2 text-sm leading-7 text-slate-600">Each mode is explained as an idea first, then settings, uses, and traps.</p></div><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{ventilatorModes.map((mode)=><article key={mode.id} className="rounded-[2rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="rounded-2xl bg-slate-950 px-4 py-3 font-black text-white">{mode.mode}</div><div className="arabic-support mt-4 rounded-2xl bg-blue-50 p-3 text-sm leading-7">{mode.simpleIdeaArabic}</div><p className="mt-3 text-sm leading-7 text-slate-700">{mode.englishCore}</p><Mini title="Use when" items={mode.useWhen}/><Mini title="Key settings" items={mode.keySettings}/><Mini title="Avoid / pitfalls" items={mode.avoidPitfalls} danger/><div className="mt-3 rounded-2xl bg-emerald-50 p-3 text-sm font-bold leading-6 text-emerald-950">{mode.compare}</div><ProgressActions id={`vent-mode-${mode.id}`} section="Ventilator Modes" title={mode.mode}/></article>)}</div></section>
  <section className="mt-8 rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-3xl font-black text-slate-950">Masks & Interfaces</h2><p className="mt-2 text-sm leading-7 text-slate-600">Know what each interface can and cannot do. Do not delay intubation when the patient is failing.</p><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{oxygenInterfaces.map((x)=><div key={x.name} className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><h3 className="font-black text-slate-950">{x.name}</h3><p className="mt-2 text-sm font-bold text-blue-700">{x.flow}</p><p className="mt-2 text-sm leading-6 text-slate-700">{x.use}</p><div className="arabic-support mt-3 text-xs leading-6">{x.arabic}</div></div>)}</div></section>
</>}
function Mini({title,items,danger=false}:{title:string;items:string[];danger?:boolean}){return <div className={`mt-3 rounded-2xl p-3 ${danger?'bg-rose-50 text-rose-950':'bg-slate-50 text-slate-700'}`}><h3 className="text-sm font-black">{title}</h3><ul className="mt-2 space-y-1">{items.map((i)=><li key={i} className="text-sm leading-6">• {i}</li>)}</ul></div>}
