import Link from 'next/link';import { InternalPage, GlassCard } from '@/components/InternalPage';import { TopicSectionPager } from '@/components/interns/TopicSectionPager';import { AlertTriangle, Zap, Lightbulb } from 'lucide-react';
const sections=[
{id:'overview',label:'Overview / لمحة',content:(<GlassCard><h2 className="text-base font-black text-white">Surgical Basics</h2><p className="mt-2 text-sm leading-7 text-slate-400">Surgical instruments, sutures, asepsis, local anesthetics, and perioperative care — foundational knowledge every intern needs before entering the OR or performing bedside procedures.</p></GlassCard>)},
{id:'recognition',label:'Key Recognition',content:(<div className="grid gap-4 sm:grid-cols-2"><GlassCard><h3 className="text-sm font-black text-white">Surgical Instruments</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Blades 10/20/22: abdominal/thoracic skin incisions.</li><li>• Blade 11: stab incisions, arterial cut-down.</li><li>• Blade 15: fine/delicate dissection.</li><li>• Needle holders, forceps, retractors — know names and uses.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Sutures</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Absorbable: Vicryl, Monocryl, PDS — deep tissues.</li><li>• Non-absorbable: Nylon, Prolene, Silk — skin, vascular.</li><li>• Suture size: smaller number = thicker (0 &gt; 3-0 &gt; 6-0).</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Asepsis</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Surgical scrub: 5 min first scrub, 3 min subsequent.</li><li>• Sterile field: only sterile items within sterile area.</li><li>• Gowning and gloving: closed technique for OR.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Local Anesthetics</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Lidocaine: rapid onset, max 4.5 mg/kg (7 mg/kg with epinephrine).</li><li>• Bupivacaine: longer duration, max 2 mg/kg.</li><li>• Toxicity: perioral tingling, tinnitus, seizures, cardiac arrest.</li></ul></GlassCard></div>)},
{id:'redflags',label:'Red Flags',content:(<GlassCard className="border-red-500/10 bg-red-500/3"><h2 className="flex items-center gap-2 text-base font-black text-red-300"><AlertTriangle size={18}/> Red Flags</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• LA toxicity: perioral numbness, tinnitus → stop, give lipid emulsion.</li><li>• Break in sterile technique → stop, re-prep, re-drape.</li><li>• Wrong-site surgery → universal protocol (timeout) prevents this.</li></ul></GlassCard>)},
{id:'nextstep',label:'Best Next Step',content:(<GlassCard><h3 className="text-sm font-black text-white">Pre-op Checklist</h3><p className="mt-2 text-sm leading-7 text-slate-400">1. Consent obtained and documented.<br />2. Site marked, laterality confirmed.<br />3. Allergies checked, antibiotics given if indicated.<br />4. NPO status confirmed.<br />5. DVT prophylaxis ordered.<br />6. Surgical timeout performed.</p></GlassCard>)},
{id:'traps',label:'Exam Traps',content:(<GlassCard><h2 className="flex items-center gap-2 text-base font-black text-white"><Zap size={18} className="text-amber-400"/> Common Exam Traps</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Confusing suture types — absorbable vs. non-absorbable is a classic Q.</li><li>• Local anesthetic dose calculation errors (watch for mg/kg limits).</li><li>• Forgetting DVT prophylaxis in surgical patients.</li></ul></GlassCard>)},
{id:'arabic',label:'Arabic / عربي',content:(<GlassCard className="border-cyan-500/15 bg-cyan-500/3"><h2 className="flex items-center gap-2 text-base font-black text-cyan-300"><Lightbulb size={18}/> Arabic Explanation</h2><p className="mt-3 text-sm leading-8 text-slate-400">أساسيات الجراحة: أنواع المشارط (10 للبطن، 11 للشق الصغير، 15 للتشريح الناعم). الخيوط: فايكريل للأنسجة العميقة، نايلون للجلد. الليدوكائين أقصى جرعة 4.5 ملغ/كغ بدون أدرينالين. التسمم بالمخدر الموضعي: تنميل حول الفم → أوقف الحقن فورًا.</p></GlassCard>)},
{id:'related',label:'Related',content:(<div className="text-center"><p className="text-xs font-bold text-slate-500">Related:</p><div className="mt-2 flex flex-wrap justify-center gap-2"><Link href="/interns/study/surgery/wounds-infections" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Wounds & Infections</Link><Link href="/interns/study/surgery/procedures" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Procedures</Link></div></div>)},
];
export default function SurgicalBasicsPage(){return(<InternalPage title="Surgical Basics" subtitle="أساسيات الجراحة" introText="Instruments, sutures, asepsis, and local anesthetics. Foundational knowledge for OR and bedside procedures." backHref="/interns/study/surgery" backLabel="Surgery"><TopicSectionPager sections={sections}/></InternalPage>);}
