import Link from 'next/link';import { InternalPage, GlassCard } from '@/components/InternalPage';import { TopicSectionPager } from '@/components/interns/TopicSectionPager';import { AlertTriangle, Zap, Lightbulb, Activity } from 'lucide-react';
const sections=[
{id:'overview',label:'Overview / لمحة',content:(<GlassCard><h2 className="text-base font-black text-white">Acute Abdomen</h2><p className="mt-2 text-sm leading-7 text-slate-400">Appendicitis, cholecystitis, intestinal obstruction, peritonitis, and surgical red flags — one of the most tested surgical topics (~20-25% of exam). Focus on pattern recognition, differentiation, and safe first-step decisions.</p><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Acute abdomen is the highest-yield surgical presentation in exams.</li><li>• Differentiating surgical vs. medical abdomen is a core intern skill.</li><li>• Best next step: NPO, IV fluids, analgesia, surgical consult.</li></ul></GlassCard>)},
{id:'recognition',label:'Key Recognition',content:(<div className="grid gap-4 sm:grid-cols-2"><GlassCard><h3 className="text-sm font-black text-white">Appendicitis</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Periumbilical pain migrating to RLQ. McBurney point tenderness.</li><li>• Rovsing sign, psoas sign, obturator sign. Low-grade fever, anorexia.</li><li>• CT abdomen diagnostic. Alvarado score for risk stratification.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Cholecystitis</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• RUQ pain after fatty meals, radiating to right shoulder.</li><li>• Murphy sign positive. Fever, leukocytosis, elevated ALP/bilirubin.</li><li>• US first: gallstones, thickened wall, pericholecystic fluid.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Intestinal Obstruction</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Colicky pain, distension, vomiting, obstipation.</li><li>• Small bowel: earlier vomiting. Large bowel: marked distension.</li><li>• X-ray: dilated loops, air-fluid levels. CT for transition point.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Peritonitis</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Severe constant pain, board-like rigidity, rebound tenderness.</li><li>• Free air under diaphragm on erect CXR = perforation.</li><li>• Emergency laparotomy after resuscitation.</li></ul></GlassCard></div>)},
{id:'redflags',label:'Red Flags',content:(<GlassCard className="border-red-500/10 bg-red-500/3"><h2 className="flex items-center gap-2 text-base font-black text-red-300"><AlertTriangle size={18}/> Red Flags</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Board-like rigidity + absent bowel sounds → surgical emergency.</li><li>• Free air on imaging → perforated viscus, urgent laparotomy.</li><li>• Hypotension + acute abdomen → ruptured AAA, mesenteric ischemia.</li><li>• Acute abdomen in elderly → consider mesenteric ischemia, AAA, malignancy.</li></ul></GlassCard>)},
{id:'nextstep',label:'Best Next Step',content:(<GlassCard><h3 className="text-sm font-black text-white">Acute Abdomen Approach</h3><p className="mt-2 text-sm leading-7 text-slate-400">1. ABCDE, IV access, monitor vitals.<br />2. NPO, IV fluids, analgesia (opiates are safe and do NOT mask signs).<br />3. Labs: CBC, electrolytes, LFTs, lipase, lactate, blood culture.<br />4. Imaging: erect CXR (free air), US (gallbladder, appendix), CT abdomen.<br />5. Surgical consult early if surgical cause suspected.</p></GlassCard>)},
{id:'traps',label:'Exam Traps',content:(<GlassCard><h2 className="flex items-center gap-2 text-base font-black text-white"><Zap size={18} className="text-amber-400"/> Common Exam Traps</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Delaying analgesia — opiates do NOT mask peritoneal signs.</li><li>• Missing AAA in elderly male with back/flank pain and hypotension.</li><li>• Discharging "non-specific abdominal pain" without surgical review.</li></ul></GlassCard>)},
{id:'arabic',label:'Arabic / عربي',content:(<GlassCard className="border-cyan-500/15 bg-cyan-500/3"><h2 className="flex items-center gap-2 text-base font-black text-cyan-300"><Lightbulb size={18}/> Arabic Explanation</h2><p className="mt-3 text-sm leading-8 text-slate-400">البطن الحاد: ألم بطن حاد + علامات بريتونية. أهم خطوة: تقييم سريع، كانيولا، سوائل، مسكّن (لا تخاف تعطي أفيونات)، وتحويل الجراح فورًا. إذا في هوا حر تحت الحجاب = ثقب أحشاء = عملية طارئة.</p></GlassCard>)},
{id:'related',label:'Related',content:(<div className="text-center"><p className="text-xs font-bold text-slate-500">Related:</p><div className="mt-2 flex flex-wrap justify-center gap-2"><Link href="/interns/study/surgery/fluids-electrolytes-transfusion" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Fluids & Electrolytes</Link><Link href="/interns/drug-essentials" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Drug Essentials</Link></div></div>)},
];
export default function AcuteAbdomenPage(){return(<InternalPage title="Acute Abdomen" subtitle="البطن الحاد في الامتياز" introText="Appendicitis, cholecystitis, obstruction, peritonitis, and surgical red flags. Focus on pattern recognition and safe first-step decisions." backHref="/interns/study/surgery" backLabel="Surgery"><TopicSectionPager sections={sections}/></InternalPage>);}
