import Link from 'next/link';import { InternalPage, GlassCard } from '@/components/InternalPage';import { TopicSectionPager } from '@/components/interns/TopicSectionPager';import { AlertTriangle, Zap, Lightbulb } from 'lucide-react';
const sections=[
{id:'overview',label:'Overview / لمحة',content:(<GlassCard><h2 className="text-base font-black text-white">Contraception & Oncology Basics</h2><p className="mt-2 text-sm leading-7 text-slate-400">Contraception contraindications, cervical cancer screening concepts, and gynecologic oncology basics — lower exam weight but consistently tested. Interns must know the major contraindications and red flags.</p></GlassCard>)},
{id:'recognition',label:'Key Recognition',content:(<div className="grid gap-4 sm:grid-cols-2"><GlassCard><h3 className="text-sm font-black text-white">Contraception Contraindications</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• COCP: smoking &gt;35, migraine with aura, VTE history, breast cancer, liver disease.</li><li>• IUD: current PID, unexplained vaginal bleeding, uterine anomaly.</li><li>• Progesterone-only: breast cancer (current), liver disease (severe).</li><li>• Emergency contraception: levonorgestrel within 72h or ulipristal within 120h.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Cervical Cancer Screening</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Pap smear: start at age 21 (or 25 per some guidelines).</li><li>• HPV testing: primary screening in many programs.</li><li>• Abnormal results → colposcopy.</li><li>• HPV vaccine: effective against HPV 16, 18 (and others).</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Gynecologic Oncology Red Flags</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Postmenopausal bleeding → endometrial cancer until proven otherwise.</li><li>• Abdominal distension + early satiety + urinary symptoms → ovarian cancer.</li><li>• Persistent bloating &gt;2 weeks in women &gt;50 → consider ovarian cancer.</li></ul></GlassCard></div>)},
{id:'redflags',label:'Red Flags',content:(<GlassCard className="border-red-500/10 bg-red-500/3"><h2 className="flex items-center gap-2 text-base font-black text-red-300"><AlertTriangle size={18}/> Red Flags</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Postmenopausal bleeding → urgent referral for endometrial sampling.</li><li>• Pelvic mass + ascites + pleural effusion → ovarian cancer (Meigs syndrome).</li><li>• Vaginal bleeding in a child → precocious puberty or abuse, investigate.</li></ul></GlassCard>)},
{id:'nextstep',label:'Best Next Step',content:(<GlassCard><h3 className="text-sm font-black text-white">Contraception Counseling Quick Guide</h3><p className="mt-2 text-sm leading-7 text-slate-400">1. Assess medical eligibility (WHO MEC categories 1-4).<br />2. Discuss efficacy, convenience, and side effects.<br />3. COCP: check BP, smoking status, migraine history.<br />4. IUD: rule out current infection, counsel on insertion.</p></GlassCard>)},
{id:'traps',label:'Exam Traps',content:(<GlassCard><h2 className="flex items-center gap-2 text-base font-black text-white"><Zap size={18} className="text-amber-400"/> Common Exam Traps</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Prescribing COCP to a woman &gt;35 who smokes (absolute contraindication).</li><li>• Not investigating postmenopausal bleeding promptly.</li><li>• Confusing absolute vs. relative contraindications for contraception.</li></ul></GlassCard>)},
{id:'arabic',label:'Arabic / عربي',content:(<GlassCard className="border-cyan-500/15 bg-cyan-500/3"><h2 className="flex items-center gap-2 text-base font-black text-cyan-300"><Lightbulb size={18}/> Arabic Explanation</h2><p className="mt-3 text-sm leading-8 text-slate-400">موانع الحمل الفموية: ممنوعة لمن تدخن وعمرها فوق 35، أو لديها شقيقة مع هالة، أو تاريخ خثار. نزيف بعد سن اليأس = استبعاد سرطان بطانة الرحم فورًا. انتفاخ بطن مستمر + شبع مبكر + أعراض بولية = فكري بسرطان المبيض.</p></GlassCard>)},
{id:'related',label:'Related',content:(<div className="text-center"><p className="text-xs font-bold text-slate-500">Related:</p><div className="mt-2 flex flex-wrap justify-center gap-2"><Link href="/interns/study/obgyn/gynecologic-emergencies" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Gynecologic Emergencies</Link><Link href="/interns/study/obgyn/early-pregnancy-bleeding" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Early Pregnancy Bleeding</Link></div></div>)},
];
export default function ContraOncPage(){return(<InternalPage title="Contraception & Oncology" subtitle="منع الحمل وأساسيات الأورام النسائية" introText="Contraindications, cervical screening, and gynecologic oncology red flags. Lower weight but consistently tested." backHref="/interns/study/obgyn" backLabel="OB/GYN"><TopicSectionPager sections={sections}/></InternalPage>);}
