'use client';
import { useMemo, useState } from 'react';
import { SectionFeatureHero } from '@/components/SectionFeatureHero';
import { getAllQuestionItems } from '@/lib/database';
import { Button } from '@/components/Button';
import { MCQEngine } from '@/components/MCQEngine';
type Mode='real'|'learning';
function pick(all:any[], topics:string[], count:number){const filtered=topics.length?all.filter(q=>topics.includes(q.topic)):all; return [...filtered].sort(()=>Math.random()-0.5).slice(0,count)}
export default function ExamYourselfPage(){const all=useMemo(()=>getAllQuestionItems(),[]); const topicOptions=useMemo(()=>Array.from(new Set(all.map(q=>q.topic))).slice(0,100),[all]); const [selected,setSelected]=useState<string[]>([]); const [count,setCount]=useState(10); const [mode,setMode]=useState<Mode>('real'); const [questions,setQuestions]=useState<any[]>([]); const start=()=>setQuestions(pick(all,selected,count)); return <><SectionFeatureHero title="Exam Yourself" subtitle="Build a real MCQ exam by choosing readable medical topics, question count, and mode. No written answers here—this is a selectable-options exam system." arabic="اختبر نفسك بخيارات واضحة، ثم اعرف أين أخطأت ولماذا." tone="emerald"/>{!questions.length?<section className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-2xl font-black text-slate-950">Build your exam</h2><div className="mt-5 grid gap-5 lg:grid-cols-3"><label><span className="text-sm font-bold text-slate-700">Number of questions</span><input type="number" min={5} max={50} value={count} onChange={(e)=>setCount(Number(e.target.value))} className="mt-2 w-full rounded-2xl border border-slate-200 px-4 py-3"/></label><label><span className="text-sm font-bold text-slate-700">Exam mode</span><select value={mode} onChange={(e)=>setMode(e.target.value as Mode)} className="mt-2 w-full rounded-2xl border border-slate-200 px-4 py-3"><option value="real">Real Exam Mode</option><option value="learning">Learning Mode</option></select></label><div className="flex items-end"><Button onClick={start}>Start Exam</Button></div></div><div className="mt-6"><div className="mb-2 text-sm font-bold text-slate-700">Select topics</div><div className="flex max-h-72 flex-wrap gap-2 overflow-y-auto rounded-2xl border border-slate-200 p-3">{topicOptions.map(t=><button key={t} onClick={()=>setSelected(p=>p.includes(t)?p.filter(x=>x!==t):[...p,t])} className={`rounded-full px-3 py-2 text-xs font-bold transition ${selected.includes(t)?'bg-emerald-600 text-white':'bg-slate-100 text-slate-700 hover:bg-emerald-50'}`}>{t}</button>)}</div></div></section>:<MCQEngine questions={questions} mode={mode} attemptType="Exam Yourself" onRestart={()=>setQuestions([])}/>}</>}
