import Link from 'next/link';import { InternalPage, GlassCard } from '@/components/InternalPage';import { TopicSectionPager } from '@/components/interns/TopicSectionPager';import { AlertTriangle, Zap, Lightbulb, HeartPulse } from 'lucide-react';
const sections=[
{id:'overview',label:'Overview / لمحة',content:(<GlassCard><h2 className="text-base font-black text-white">Neonatal Emergencies</h2><p className="mt-2 text-sm leading-7 text-slate-400">Neonatal danger signs, jaundice, sepsis, and resuscitation basics — distinct from adult medicine and frequently tested (~15-20% of exam). Focus on recognition, APGAR, and when to escalate.</p><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• APGAR scoring, neonatal jaundice, and sepsis are the most tested.</li><li>• Interns in ED/nursery must recognise the sick newborn and escalate early.</li></ul></GlassCard>)},
{id:'recognition',label:'Key Recognition',content:(<div className="grid gap-4 sm:grid-cols-2"><GlassCard><h3 className="text-sm font-black text-white">APGAR Scoring</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Appearance: 0=blue, 1=body pink/ext blue, 2=all pink.</li><li>• Pulse: 0=absent, 1=&lt;100, 2=≥100.</li><li>• Grimace: 0=none, 1=grimace, 2=cough/sneeze/cry.</li><li>• Activity: 0=limp, 1=some flexion, 2=active.</li><li>• Respiration: 0=absent, 1=slow/irregular, 2=good/crying.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Neonatal Jaundice</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Physiological: day 2-3, peaks day 2-3, resolves by day 5-7.</li><li>• Pathological: first 24h, rate &gt;5 mg/dL/day, peak &gt;13 mg/dL.</li><li>• Most common cause in first 24h: hemolytic disease.</li><li>• Exchange transfusion if &gt;20-25 mg/dL or kernicterus signs.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Neonatal Sepsis</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• GBS most common, then E. coli.</li><li>• Signs: poor feeding, lethargy, temperature instability.</li><li>• Empiric: ampicillin + gentamicin (or cefotaxime).</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Congenital Diaphragmatic Hernia</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Respiratory distress + scaphoid abdomen + bowel sounds in chest.</li><li>• Left side 80%. Do NOT bag-mask → gastric distension.</li><li>• Immediate intubation + NG tube. Surgical correction when stable.</li></ul></GlassCard></div>)},
{id:'redflags',label:'Red Flags',content:(<GlassCard className="border-red-500/10 bg-red-500/3"><h2 className="flex items-center gap-2 text-base font-black text-red-300"><AlertTriangle size={18}/> Red Flags</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Jaundice in first 24h → always pathological.</li><li>• Bilirubin &gt;20 mg/dL in term → exchange transfusion.</li><li>• Fever in neonate (&lt;28 days) → full septic workup + admit + IV antibiotics.</li><li>• Respiratory distress + scaphoid abdomen → CDH, intubate immediately.</li></ul></GlassCard>)},
{id:'nextstep',label:'Best Next Step',content:(<GlassCard><h3 className="text-sm font-black text-white">Neonatal Resuscitation</h3><p className="mt-2 text-sm leading-7 text-slate-400">1. Dry, stimulate, warm (30s).<br />2. If HR &lt;100 or gasping: PPV.<br />3. If HR &lt;60 despite PPV: chest compressions.<br />4. If HR &lt;60 despite compressions + PPV: epinephrine.</p></GlassCard>)},
{id:'traps',label:'Exam Traps',content:(<GlassCard><h2 className="flex items-center gap-2 text-base font-black text-white"><Zap size={18} className="text-amber-400"/> Common Exam Traps</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Confusing physiological vs. pathological jaundice — timing is key.</li><li>• Stopping breastfeeding for breast milk jaundice — not required.</li><li>• Missing CDH — never bag-mask these infants.</li></ul></GlassCard>)},
{id:'arabic',label:'Arabic / عربي',content:(<GlassCard className="border-cyan-500/15 bg-cyan-500/3"><h2 className="flex items-center gap-2 text-base font-black text-cyan-300"><Lightbulb size={18}/> Arabic Explanation</h2><p className="mt-3 text-sm leading-8 text-slate-400">اليرقان خلال أول 24 ساعة دائمًا مرضي. أي مولود عنده حرارة أول 28 يوم = تنويم + مضادات وريدية. فتق الحجاب الحاجز: لا تستعمل الكيس والكمام أبدًا — أنبوب تنفسي فورًا. أهم ثلاث: اليرقان، الإنتان، CDH.</p></GlassCard>)},
{id:'related',label:'Related',content:(<div className="text-center"><p className="text-xs font-bold text-slate-500">Related:</p><div className="mt-2 flex flex-wrap justify-center gap-2"><Link href="/interns/study/pediatrics/respiratory-emergencies" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Respiratory Emergencies</Link><Link href="/interns/study/pediatrics/red-flags" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Red Flags</Link></div></div>)},
];
export default function NeonatalEmergenciesPage(){return(<InternalPage title="Neonatal Emergencies" subtitle="طوارئ حديثي الولادة" introText="Danger signs, jaundice, sepsis, Apgar, and CDH. Focus on recognition and when to escalate." backHref="/interns/study/pediatrics" backLabel="Pediatrics"><TopicSectionPager sections={sections}/></InternalPage>);}
