import Link from 'next/link';import { InternalPage, GlassCard } from '@/components/InternalPage';import { TopicSectionPager } from '@/components/interns/TopicSectionPager';import { AlertTriangle, Zap, Lightbulb } from 'lucide-react';
const sections=[
{id:'overview',label:'Overview / لمحة',content:(<GlassCard><h2 className="text-base font-black text-white">Hypertensive Disorders in Pregnancy</h2><p className="mt-2 text-sm leading-7 text-slate-400">Preeclampsia, eclampsia, HELLP syndrome, and magnesium sulfate — hypertensive disorders are a leading cause of maternal mortality. Interns must recognize warning signs and initiate treatment quickly.</p></GlassCard>)},
{id:'recognition',label:'Key Recognition',content:(<div className="grid gap-4 sm:grid-cols-2"><GlassCard><h3 className="text-sm font-black text-white">Preeclampsia</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Hypertension (SBP &ge;140 or DBP &ge;90) after 20 weeks + proteinuria.</li><li>• Severe features: SBP &ge;160, DBP &ge;110, headache, visual changes, RUQ pain, oliguria.</li><li>• Delivery is the definitive treatment.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Eclampsia</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Preeclampsia + generalized tonic-clonic seizure.</li><li>• Magnesium sulfate 4-6 g IV load + infusion for seizure prophylaxis/treatment.</li><li>• Monitor: respiratory rate, reflexes, urine output (Mg toxicity).</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">HELLP Syndrome</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Hemolysis, Elevated Liver enzymes, Low Platelets.</li><li>• RUQ/epigastric pain, nausea, malaise.</li><li>• Treatment: delivery. Platelet transfusion if &lt;50K and bleeding/procedure.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">BP Management</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Acute severe: labetalol IV, hydralazine IV, or nifedipine PO.</li><li>• Target: reduce by 25% in first hour, not to normal.</li><li>• Avoid rapid drops → placental hypoperfusion.</li></ul></GlassCard></div>)},
{id:'redflags',label:'Red Flags',content:(<GlassCard className="border-red-500/10 bg-red-500/3"><h2 className="flex items-center gap-2 text-base font-black text-red-300"><AlertTriangle size={18}/> Red Flags</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Seizure in pregnant patient → eclampsia, MgSO4 STAT.</li><li>• RUQ pain + N/V + hypertension → HELLP, urgent delivery.</li><li>• Severe headache + visual changes in preeclampsia → impending eclampsia.</li></ul></GlassCard>)},
{id:'nextstep',label:'Best Next Step',content:(<GlassCard><h3 className="text-sm font-black text-white">Eclampsia Management</h3><p className="mt-2 text-sm leading-7 text-slate-400">1. ABCDE, left lateral position, O2.<br />2. Magnesium sulfate: 4-6 g IV over 15-20 min, then 1-2 g/h infusion.<br />3. Control BP: labetalol 20 mg IV, repeat as needed.<br />4. Monitor Mg toxicity: loss of reflexes (first sign), respiratory depression, cardiac arrest.<br />5. Antidote: calcium gluconate.</p></GlassCard>)},
{id:'traps',label:'Exam Traps',content:(<GlassCard><h2 className="flex items-center gap-2 text-base font-black text-white"><Zap size={18} className="text-amber-400"/> Common Exam Traps</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Giving MgSO4 without monitoring reflexes and respiratory rate.</li><li>• Missing HELLP in a patient with epigastric pain (not just RUQ).</li><li>• Not checking urine protein in hypertensive pregnant patient.</li></ul></GlassCard>)},
{id:'arabic',label:'Arabic / عربي',content:(<GlassCard className="border-cyan-500/15 bg-cyan-500/3"><h2 className="flex items-center gap-2 text-base font-black text-cyan-300"><Lightbulb size={18}/> Arabic Explanation</h2><p className="mt-3 text-sm leading-8 text-slate-400">تسمم الحمل: ضغط مرتفع بعد 20 أسبوع + بروتين في البول. النوبة الارتعاجية: تشنج + ارتفاع ضغط = مغنيسيوم 4-6 غ وريديًا. مراقبة سمية المغنيسيوم: اختفاء المنعكسات هو أول علامة — الترياق: غلوكونات الكالسيوم.</p></GlassCard>)},
{id:'related',label:'Related',content:(<div className="text-center"><p className="text-xs font-bold text-slate-500">Related:</p><div className="mt-2 flex flex-wrap justify-center gap-2"><Link href="/interns/study/obgyn/early-pregnancy-bleeding" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Early Pregnancy Bleeding</Link><Link href="/interns/study/obgyn/postpartum-hemorrhage" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Postpartum Hemorrhage</Link></div></div>)},
];
export default function HDPPage(){return(<InternalPage title="Hypertensive Disorders" subtitle="اضطرابات ارتفاع الضغط في الحمل" introText="Preeclampsia, eclampsia, HELLP, and magnesium sulfate. Leading cause of maternal mortality." backHref="/interns/study/obgyn" backLabel="OB/GYN"><TopicSectionPager sections={sections}/></InternalPage>);}
