begin;

create table if not exists public.professional_credential_submissions (
  id uuid primary key,
  owner_user_id uuid not null
    constraint professional_credential_submissions_owner_user_id_fkey
    references public.profiles(id) on delete cascade,
  credential_type text not null,
  document_title text not null,
  issuing_authority text,
  license_number text,
  country text,
  issue_date date,
  expiry_date date,
  document_path text not null unique,
  original_filename text not null,
  mime_type text not null,
  file_size_bytes bigint not null,
  submission_status text not null default 'submitted',
  submitted_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid
    constraint professional_credential_submissions_reviewed_by_fkey
    references public.profiles(id) on delete set null,
  review_note text,
  created_at timestamptz not null default now()
);

alter table public.professional_credential_submissions
  drop constraint if exists professional_credential_submissions_status_check;

alter table public.professional_credential_submissions
  add constraint professional_credential_submissions_status_check
  check (
    submission_status in (
      'submitted',
      'under_review',
      'needs_changes',
      'verified',
      'rejected',
      'revoked'
    )
  );

alter table public.professional_credential_submissions
  drop constraint if exists professional_credential_submissions_document_path_check;

alter table public.professional_credential_submissions
  add constraint professional_credential_submissions_document_path_check
  check (
    split_part(document_path, '/', 1) = owner_user_id::text
  );

alter table public.professional_credential_submissions
  drop constraint if exists professional_credential_submissions_mime_type_check;

alter table public.professional_credential_submissions
  add constraint professional_credential_submissions_mime_type_check
  check (
    mime_type in (
      'application/pdf',
      'image/jpeg',
      'image/png'
    )
  );

alter table public.professional_credential_submissions
  drop constraint if exists professional_credential_submissions_file_size_check;

alter table public.professional_credential_submissions
  add constraint professional_credential_submissions_file_size_check
  check (
    file_size_bytes > 0
    and file_size_bytes <= 10485760
  );

alter table public.professional_credential_submissions
  drop constraint if exists professional_credential_submissions_date_check;

alter table public.professional_credential_submissions
  add constraint professional_credential_submissions_date_check
  check (
    expiry_date is null
    or issue_date is null
    or expiry_date >= issue_date
  );

create index if not exists
  professional_credential_submissions_owner_idx
on public.professional_credential_submissions (
  owner_user_id,
  created_at desc
);

create index if not exists
  professional_credential_submissions_status_idx
on public.professional_credential_submissions (
  submission_status,
  created_at desc
);

alter table public.professional_credential_submissions
  enable row level security;

drop policy if exists
  professional_credential_submissions_owner_or_admin_select
on public.professional_credential_submissions;

create policy
  professional_credential_submissions_owner_or_admin_select
on public.professional_credential_submissions
for select
to authenticated
using (
  owner_user_id = auth.uid()
  or private.is_admin()
);

drop policy if exists
  professional_credential_submissions_admin_update
on public.professional_credential_submissions;

create policy
  professional_credential_submissions_admin_update
on public.professional_credential_submissions
for update
to authenticated
using (private.is_admin())
with check (private.is_admin());

revoke all
on table public.professional_credential_submissions
from anon;

revoke insert, delete
on table public.professional_credential_submissions
from authenticated;

grant select, update
on table public.professional_credential_submissions
to authenticated;

create table if not exists
  public.professional_credential_review_events (
    id bigint generated by default as identity primary key,
    submission_id uuid not null
      references public.professional_credential_submissions(id)
      on delete cascade,
    owner_user_id uuid not null
      references public.profiles(id)
      on delete cascade,
    actor_user_id uuid
      references public.profiles(id)
      on delete set null,
    previous_status text not null,
    new_status text not null,
    review_note text,
    created_at timestamptz not null default now()
  );

create index if not exists
  professional_credential_review_events_submission_idx
on public.professional_credential_review_events (
  submission_id,
  created_at desc
);

alter table public.professional_credential_review_events
  enable row level security;

drop policy if exists
  professional_credential_review_events_admin_select
on public.professional_credential_review_events;

create policy
  professional_credential_review_events_admin_select
on public.professional_credential_review_events
for select
to authenticated
using (private.is_admin());

revoke all
on table public.professional_credential_review_events
from anon, authenticated;

grant select
on table public.professional_credential_review_events
to authenticated;

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'credential-documents',
  'credential-documents',
  false,
  10485760,
  array[
    'application/pdf',
    'image/jpeg',
    'image/png'
  ]
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists
  credential_submission_owner_or_admin_read
on storage.objects;

create policy
  credential_submission_owner_or_admin_read
on storage.objects
for select
to authenticated
using (
  bucket_id = 'credential-documents'
  and (
    (storage.foldername(name))[1] = auth.uid()::text
    or private.is_admin()
  )
);

drop policy if exists
  credential_submission_owner_insert
on storage.objects;

create policy
  credential_submission_owner_insert
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'credential-documents'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists
  credential_submission_unregistered_owner_delete
on storage.objects;

create policy
  credential_submission_unregistered_owner_delete
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'credential-documents'
  and (storage.foldername(name))[1] = auth.uid()::text
  and not exists (
    select 1
    from public.professional_credential_submissions submission
    where submission.document_path = name
  )
);

create or replace function
  public.submit_professional_credential_submission(
    p_id uuid,
    p_credential_type text,
    p_document_title text,
    p_issuing_authority text,
    p_license_number text,
    p_country text,
    p_issue_date date,
    p_expiry_date date,
    p_document_path text,
    p_original_filename text,
    p_mime_type text,
    p_file_size_bytes bigint
  )
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
  normalized_type text := nullif(trim(p_credential_type), '');
  normalized_title text := nullif(trim(p_document_title), '');
begin
  if current_user_id is null then
    raise exception 'Authentication is required.'
      using errcode = '42501';
  end if;

  if p_id is null then
    raise exception 'Submission identifier is required.'
      using errcode = '22023';
  end if;

  if normalized_type is null
     or char_length(normalized_type) > 100 then
    raise exception 'A valid credential type is required.'
      using errcode = '22023';
  end if;

  if normalized_title is null
     or char_length(normalized_title) > 200 then
    raise exception 'A valid document title is required.'
      using errcode = '22023';
  end if;

  if split_part(p_document_path, '/', 1)
     <> current_user_id::text then
    raise exception 'Invalid document path.'
      using errcode = '42501';
  end if;

  if p_mime_type not in (
    'application/pdf',
    'image/jpeg',
    'image/png'
  ) then
    raise exception 'Unsupported document type.'
      using errcode = '22023';
  end if;

  if p_file_size_bytes <= 0
     or p_file_size_bytes > 10485760 then
    raise exception 'Document size is invalid.'
      using errcode = '22023';
  end if;

  if p_issue_date is not null
     and p_expiry_date is not null
     and p_expiry_date < p_issue_date then
    raise exception 'Expiry date cannot precede issue date.'
      using errcode = '22023';
  end if;

  if not exists (
    select 1
    from storage.objects object
    where object.bucket_id = 'credential-documents'
      and object.name = p_document_path
  ) then
    raise exception 'Uploaded document was not found.'
      using errcode = 'P0002';
  end if;

  insert into public.professional_credential_submissions (
    id,
    owner_user_id,
    credential_type,
    document_title,
    issuing_authority,
    license_number,
    country,
    issue_date,
    expiry_date,
    document_path,
    original_filename,
    mime_type,
    file_size_bytes,
    submission_status
  )
  values (
    p_id,
    current_user_id,
    normalized_type,
    normalized_title,
    nullif(trim(p_issuing_authority), ''),
    nullif(trim(p_license_number), ''),
    nullif(trim(p_country), ''),
    p_issue_date,
    p_expiry_date,
    p_document_path,
    left(trim(p_original_filename), 255),
    p_mime_type,
    p_file_size_bytes,
    'submitted'
  );

  update public.profiles
  set
    professional_verification_status = 'submitted',
    professional_verification_review_note = null,
    professional_verification_reviewed_at = null,
    professional_verification_reviewed_by = null
  where id = current_user_id;

  return p_id;
end;
$$;

revoke all
on function public.submit_professional_credential_submission(
  uuid,
  text,
  text,
  text,
  text,
  text,
  date,
  date,
  text,
  text,
  text,
  bigint
)
from public, anon;

grant execute
on function public.submit_professional_credential_submission(
  uuid,
  text,
  text,
  text,
  text,
  text,
  date,
  date,
  text,
  text,
  text,
  bigint
)
to authenticated;

create or replace function
  public.review_professional_credential_submission(
    p_submission_id uuid,
    p_new_status text,
    p_review_note text
  )
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
  submission_owner_id uuid;
  old_status text;
  derived_profile_status text;
  normalized_note text :=
    nullif(left(trim(coalesce(p_review_note, '')), 2000), '');
begin
  if current_user_id is null
     or not private.is_admin() then
    raise exception 'Active Admin access is required.'
      using errcode = '42501';
  end if;

  if p_new_status not in (
    'submitted',
    'under_review',
    'needs_changes',
    'verified',
    'rejected',
    'revoked'
  ) then
    raise exception 'Invalid review status.'
      using errcode = '22023';
  end if;

  select
    submission.owner_user_id,
    submission.submission_status
  into
    submission_owner_id,
    old_status
  from public.professional_credential_submissions submission
  where submission.id = p_submission_id
  for update;

  if submission_owner_id is null then
    raise exception 'Credential submission was not found.'
      using errcode = 'P0002';
  end if;

  if submission_owner_id = current_user_id then
    raise exception
      'Another Admin must review this credential submission.'
      using errcode = '42501';
  end if;

  update public.professional_credential_submissions
  set
    submission_status = p_new_status,
    review_note = normalized_note,
    reviewed_at = now(),
    reviewed_by = current_user_id,
    updated_at = now()
  where id = p_submission_id;

  insert into public.professional_credential_review_events (
    submission_id,
    owner_user_id,
    actor_user_id,
    previous_status,
    new_status,
    review_note
  )
  values (
    p_submission_id,
    submission_owner_id,
    current_user_id,
    old_status,
    p_new_status,
    normalized_note
  );

  select
    case
      when bool_or(submission_status = 'verified')
        then 'verified'
      when bool_or(submission_status = 'under_review')
        then 'under_review'
      when bool_or(submission_status = 'submitted')
        then 'submitted'
      when bool_or(submission_status = 'needs_changes')
        then 'needs_changes'
      when bool_or(submission_status = 'rejected')
        then 'rejected'
      when bool_or(submission_status = 'revoked')
        then 'revoked'
      else 'not_submitted'
    end
  into derived_profile_status
  from public.professional_credential_submissions
  where owner_user_id = submission_owner_id;

  update public.profiles
  set
    professional_verification_status =
      coalesce(derived_profile_status, 'not_submitted'),
    professional_verification_review_note = normalized_note,
    professional_verification_reviewed_at = now(),
    professional_verification_reviewed_by = current_user_id
  where id = submission_owner_id;
end;
$$;

revoke all
on function public.review_professional_credential_submission(
  uuid,
  text,
  text
)
from public, anon;

grant execute
on function public.review_professional_credential_submission(
  uuid,
  text,
  text
)
to authenticated;

create or replace function private.protect_profile_security_fields()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  protected_fields_changed boolean;
  verification_fields_changed boolean;
  allowed_submission_transition boolean;
begin
  if auth.uid() is not null
     and old.phone is not null
     and new.phone is distinct from old.phone then
    raise exception
      'Phone number cannot be changed from an authenticated client'
      using errcode = '42501';
  end if;

  if auth.uid() is not null
     and not private.is_admin() then
    protected_fields_changed := row(
      new.id,
      new.email,
      new.role,
      new.admin_level,
      new.status,
      new.account_status,
      new.subscription_status,
      new.educator_status,
      new.ai_enabled,
      new.reviewed_at,
      new.reviewed_by,
      new.review_note,
      new.created_at
    ) is distinct from row(
      old.id,
      old.email,
      old.role,
      old.admin_level,
      old.status,
      old.account_status,
      old.subscription_status,
      old.educator_status,
      old.ai_enabled,
      old.reviewed_at,
      old.reviewed_by,
      old.review_note,
      old.created_at
    );

    if protected_fields_changed then
      raise exception
        'Protected profile fields cannot be changed by this user'
        using errcode = '42501';
    end if;

    verification_fields_changed := row(
      new.professional_verification_status,
      new.professional_verification_review_note,
      new.professional_verification_reviewed_at,
      new.professional_verification_reviewed_by
    ) is distinct from row(
      old.professional_verification_status,
      old.professional_verification_review_note,
      old.professional_verification_reviewed_at,
      old.professional_verification_reviewed_by
    );

    if verification_fields_changed then
      allowed_submission_transition :=
        new.id = auth.uid()
        and new.professional_verification_status = 'submitted'
        and old.professional_verification_status in (
          'not_submitted',
          'draft',
          'submitted',
          'needs_changes',
          'rejected',
          'expired'
        )
        and new.professional_verification_review_note is null
        and new.professional_verification_reviewed_at is null
        and new.professional_verification_reviewed_by is null
        and exists (
          select 1
          from public.professional_credential_submissions submission
          where submission.owner_user_id = auth.uid()
            and submission.submission_status = 'submitted'
        );

      if not allowed_submission_transition then
        raise exception
          'Professional verification fields cannot be changed directly'
          using errcode = '42501';
      end if;
    end if;
  end if;

  return new;
end;
$$;

revoke all
on function private.protect_profile_security_fields()
from public, anon, authenticated;

commit;