import Link from 'next/link';import { InternalPage, GlassCard } from '@/components/InternalPage';import { TopicSectionPager } from '@/components/interns/TopicSectionPager';import { AlertTriangle, Zap, Lightbulb } from 'lucide-react';
const sections=[
{id:'overview',label:'Overview / لمحة',content:(<GlassCard><h2 className="text-base font-black text-white">Pediatric Emergency Cases</h2><p className="mt-2 text-sm leading-7 text-slate-400">Common pediatric emergency presentations and safe first steps. Interns must recognize age-specific differences in presentation, assessment, and management. Children are not small adults.</p></GlassCard>)},
{id:'recognition',label:'Key Recognition',content:(<div className="grid gap-4 sm:grid-cols-2"><GlassCard><h3 className="text-sm font-black text-white">Febrile Seizure</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Age 6 months – 5 years, fever &gt;38°, generalized tonic-clonic &lt;15 min.</li><li>• Simple: &lt;15 min, no recurrence in 24h, generalized.</li><li>• Complex: &gt;15 min, focal, or recurrence in 24h.</li><li>• Treat fever. Reassure parents. LP if meningeal signs present.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Anaphylaxis</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Rapid onset after exposure: urticaria, angioedema, respiratory distress, hypotension.</li><li>• Epinephrine IM (0.01 mg/kg of 1:1000, max 0.5 mg) — first-line always.</li><li>• Then: O2, IV fluids, antihistamines, corticosteroids.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Pediatric Sepsis</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Tachycardia may be the only early sign. Capillary refill &gt;2s.</li><li>• Hypotension is a LATE sign in children.</li><li>• Antibiotics within 1h. Fluid boluses 20 mL/kg, reassess after each.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Status Epilepticus</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Check glucose immediately (hypoglycemia mimics seizure).</li><li>• Benzodiazepine: lorazepam 0.1 mg/kg IV or midazolam 0.2 mg/kg IM.</li><li>• Second-line: levetiracetam 40 mg/kg or phenytoin 20 mg/kg.</li></ul></GlassCard></div>)},
{id:'redflags',label:'Red Flags',content:(<GlassCard className="border-red-500/10 bg-red-500/3"><h2 className="flex items-center gap-2 text-base font-black text-red-300"><AlertTriangle size={18}/> Red Flags</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Hypotension in a child → decompensated shock, ICU immediately.</li><li>• Seizure &gt;5 min or incomplete recovery → status epilepticus.</li><li>• Petechial rash + fever + ill appearance → meningococcemia.</li><li>• Bradycardia + hypotension + altered mental status → impending cardiac arrest.</li></ul></GlassCard>)},
{id:'nextstep',label:'Best Next Step',content:(<GlassCard><h3 className="text-sm font-black text-white">Pediatric Emergency Approach</h3><p className="mt-2 text-sm leading-7 text-slate-400">1. Pediatric assessment triangle (appearance, breathing, circulation).<br />2. ABCDE with age-appropriate equipment.<br />3. Weight estimate: (age+4)×2 kg (1-9 yrs) or Broselow tape.<br />4. Early escalation — children decompensate faster than adults.</p></GlassCard>)},
{id:'traps',label:'Exam Traps',content:(<GlassCard><h2 className="flex items-center gap-2 text-base font-black text-white"><Zap size={18} className="text-amber-400"/> Common Exam Traps</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Relying on hypotension to diagnose pediatric shock (late sign).</li><li>• Not checking glucose in seizing child.</li><li>• Giving antihistamines before epinephrine in anaphylaxis.</li></ul></GlassCard>)},
{id:'arabic',label:'Arabic / عربي',content:(<GlassCard className="border-cyan-500/15 bg-cyan-500/3"><h2 className="flex items-center gap-2 text-base font-black text-cyan-300"><Lightbulb size={18}/> Arabic Explanation</h2><p className="mt-3 text-sm leading-8 text-slate-400">تشنج الحرارة: عمر 6 شهور لـ 5 سنوات، أقل من 15 دقيقة، عام. الأدرينالين هو الخط الأول دائمًا في الحساسية المفرطة. هبوط الضغط عند الأطفال علامة متأخرة جدًا — لا تعتمد عليه لتشخيص الصدمة. افحص السكر دائمًا في أي تشنج.</p></GlassCard>)},
{id:'related',label:'Related',content:(<div className="text-center"><p className="text-xs font-bold text-slate-500">Related:</p><div className="mt-2 flex flex-wrap justify-center gap-2"><Link href="/interns/study/pediatrics/neonatal-emergencies" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Neonatal Emergencies</Link><Link href="/interns/study/pediatrics/red-flags" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Pediatric Red Flags</Link></div></div>)},
];
export default function PedsCasesPage(){return(<InternalPage title="Pediatric Emergency Cases" subtitle="حالات طوارئ الأطفال" introText="Common pediatric emergency presentations and safe first steps. Children are not small adults." backHref="/interns/study/pediatrics" backLabel="Pediatrics"><TopicSectionPager sections={sections}/></InternalPage>);}
