import Link from 'next/link';import { InternalPage, GlassCard } from '@/components/InternalPage';import { TopicSectionPager } from '@/components/interns/TopicSectionPager';import { AlertTriangle, Zap, Lightbulb } from 'lucide-react';
const sections=[
{id:'overview',label:'Overview / لمحة',content:(<GlassCard><h2 className="text-base font-black text-white">Dehydration & Gastroenteritis</h2><p className="mt-2 text-sm leading-7 text-slate-400">One of the most common pediatric presentations. Interns must assess dehydration severity, choose between ORS and IV fluids, and recognize when a child needs admission.</p></GlassCard>)},
{id:'recognition',label:'Key Recognition',content:(<div className="grid gap-4 sm:grid-cols-2"><GlassCard><h3 className="text-sm font-black text-white">Dehydration Assessment</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Mild (&lt;5%): thirsty, normal vitals, moist mucosa.</li><li>• Moderate (5-10%): sunken eyes, decreased skin turgor, dry mucosa, irritable.</li><li>• Severe (&gt;10%): lethargic, very sunken eyes, skin pinch &gt;2s, shock.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">ORS vs. IV Fluids</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• ORS is first-line for mild-moderate dehydration.</li><li>• IV fluids: severe dehydration, shock, failed ORS, altered mental status.</li><li>• Bolus: 20 mL/kg 0.9% NaCl, reassess after each bolus.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Maintenance Fluids</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• 100/50/20 rule (daily): first 10 kg × 100, next 10 × 50, &gt;20 × 20.</li><li>• 4/2/1 rule (hourly): 4 mL/kg first 10 kg, 2 mL/kg next 10, 1 mL/kg after.</li></ul></GlassCard><GlassCard><h3 className="text-sm font-black text-white">Gastroenteritis Red Flags</h3><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-400"><li>• Bloody diarrhea → bacterial (Shigella, Campylobacter, E. coli).</li><li>• Persistent vomiting → consider other causes (obstruction, DKA, sepsis).</li><li>• Oliguria → severe dehydration, impending renal injury.</li></ul></GlassCard></div>)},
{id:'redflags',label:'Red Flags',content:(<GlassCard className="border-red-500/10 bg-red-500/3"><h2 className="flex items-center gap-2 text-base font-black text-red-300"><AlertTriangle size={18}/> Red Flags</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Lethargy + sunken eyes + skin pinch &gt;2s → severe dehydration, IV access STAT.</li><li>• Bilious vomiting in neonate → malrotation/volvulus until proven otherwise.</li><li>• Bloody diarrhea + oliguria → HUS (E. coli O157:H7), do NOT give antibiotics.</li></ul></GlassCard>)},
{id:'nextstep',label:'Best Next Step',content:(<GlassCard><h3 className="text-sm font-black text-white">Dehydration Management Plan</h3><p className="mt-2 text-sm leading-7 text-slate-400">Plan A (no dehydration): continue feeding, increased fluids.<br />Plan B (some dehydration): ORS 75 mL/kg over 4h, reassess.<br />Plan C (severe dehydration): IV 0.9% NaCl 20 mL/kg bolus, repeat as needed, admit.</p></GlassCard>)},
{id:'traps',label:'Exam Traps',content:(<GlassCard><h2 className="flex items-center gap-2 text-base font-black text-white"><Zap size={18} className="text-amber-400"/> Common Exam Traps</h2><ul className="mt-3 space-y-1.5 text-sm leading-7 text-slate-400"><li>• Giving antibiotics for bloody diarrhea (HUS contraindication).</li><li>• Using anti-diarrheals in children (contraindicated).</li><li>• Not reassessing after each fluid bolus in severe dehydration.</li></ul></GlassCard>)},
{id:'arabic',label:'Arabic / عربي',content:(<GlassCard className="border-cyan-500/15 bg-cyan-500/3"><h2 className="flex items-center gap-2 text-base font-black text-cyan-300"><Lightbulb size={18}/> Arabic Explanation</h2><p className="mt-3 text-sm leading-8 text-slate-400">الجفاف الخفيف: محلول الجفاف الفموي (ORS). الجفاف الشديد: كانيولا + 20 مل/كغ محلول ملحي وريدي، كرر حسب الحاجة. لا تعطي مضادات حيوية في الإسهال الدموي (خطر HUS). قاعدة حساب السوائل اليومية: 100/50/20.</p></GlassCard>)},
{id:'related',label:'Related',content:(<div className="text-center"><p className="text-xs font-bold text-slate-500">Related:</p><div className="mt-2 flex flex-wrap justify-center gap-2"><Link href="/interns/study/pediatrics/neonatal-emergencies" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Neonatal Emergencies</Link><Link href="/interns/study/surgery/fluids-electrolytes-transfusion" className="rounded-full border border-slate-600/30 px-3 py-1 text-[10px] font-bold text-slate-400 hover:border-cyan-500/30 hover:text-cyan-300">Fluids & Electrolytes</Link></div></div>)},
];
export default function DehydrationPage(){return(<InternalPage title="Dehydration & Gastroenteritis" subtitle="الجفاف والتهاب المعدة والأمعاء" introText="Assess severity, choose ORS vs. IV, and recognize admission criteria. One of the most common pediatric presentations." backHref="/interns/study/pediatrics" backLabel="Pediatrics"><TopicSectionPager sections={sections}/></InternalPage>);}
